INSERT INTO VehicleBaseModels (BaseModel)
VALUES
('i-280 Extended Cab'), 
('i-290 Extended Cab'), 
('i-350 Crew Cab'), 
('i-370 Crew Cab'), 
('i-370 Extended Cab'), 
('I-Mark'), 
('Impulse'), 
('Oasis'), 
('Rodeo'), 
('Stylus'), 
('Trooper'), 
('Vehicross'), 
('E-Pace'), 
('F-Pace'), 
('F-Type'), 
('I-Pace'), 
('S-Type'), 
('Super V8'), 
('Vanden Plas'), 
('Vdp'), 
('XE'), 
('XF'), 
('XJ'), 
('XJL'), 
('XJR'), 
('XJRS'), 
('XJS'), 
('XK'), 
('XK8'), 
('XKR'), 
('X-Type'), 
('W-126/4 Series'), 
('Cherokee'), 
('Cherokee/Wagoneer'), 
('CJ'), 
('Comanche'), 
('Comanche Pickup'), 
('Commander'), 
('Compass'), 
('Gladiator'), 
('Gladiator Pickup'), 
('Grand Cherokee'), 
('Grand Wagoneer'), 
('J-10 Pickup'), 
('J-20 Pickup'), 
('Liberty'), 
('Liberty/Cherokee'), 
('Wrangler'), 
('Patriot'), 
('Renegade'), 
('Scrambler'), 
('Scrambler Pickup'), 
('Wagoneer'), 
('Wrangler/TJ'), 
('K27'), 
('GS-6'), 
('Revero'), 
('Kenyon 5.0 Cabrio'), 
('Kenyon 5.0 Coupe'), 
('Kenyon 5.0 Sedan'), 
('Kenyon 5.0 Sp Sedan'), 
('Amanti'), 
('Borrego'), 
('Cadenza'), 
('Carnival'), 
('EV6'), 
('Forte'), 
('K5'), 
('K900'), 
('Niro'), 
('Optima'), 
('Rio'), 
('Rondo'), 
('Sedona'), 
('Seltos'), 
('Sephia'), 
('Sephia/Spectra'), 
('Sorento'), 
('Soul'), 
('Spectra'), 
('Sportage'), 
('Stinger'), 
('Telluride'), 
('Agera RS'), 
('Regera'), 
('Laforza'), 
('300E'), 
('Aventador'), 
('Countach'), 
('Diablo'), 
('Gallardo'), 
('Huracan'), 
('Murcielago'), 
('Urus'), 
('Veneno'), 
('Defender'), 
('Discovery'), 
('Discovery Sport'), 
('Evoque'), 
('Freelander'), 
('LR2'), 
('LR3'), 
('LR4'), 
('Range Rover'), 
('CT'), 
('ES'), 
('GS'), 
('GX'), 
('HS'), 
('IS'), 
('IS F'), 
('LC'), 
('LFA'), 
('LS'), 
('LX'), 
('NX'), 
('RC'), 
('RC F'), 
('RX'), 
('RZ'), 
('UX'), 
('Aviator'), 
('Blackwood'), 
('Corsair'), 
('Mark LT'), 
('Mark VII'), 
('Mark VIII'), 
('MKC'), 
('MKS'), 
('MKT'), 
('MKX'), 
('MKZ'), 
('Nautilus'), 
('Navigator'), 
('Town Car'), 
('Zephyr'), 
('London Taxi'), 
('Endurance'), 
('Esprit'), 
('Elan'), 
('Elise/Exige'), 
('Evora'), 
('Air'), 
('TR40'), 
('225'), 
('228'), 
('430'), 
('222E'), 
('BiTurbo'), 
('BiTurbo Spyder'), 
('Coupe and Gransport'), 
('Coupe Cambiocorsa/Coupe GT'), 
('Coupe Cambiocorsa/GT/G-Sport'), 
('Ghibli'), 
('GranTurismo'), 
('Grecale'), 
('Karif'), 
('Levante'), 
('MC20'), 
('Q'), 
('Quattroporte'), 
('Spyder'), 
('57'), 
('62'), 
('Landaulet'), 
('2'), 
('3'), 
('5'), 
('6'), 
('323'), 
('626'), 
('929'), 
('B Pickup'), 
('323 Protege'), 
('626/MX-6'), 
('CX-3'), 
('CX-30'), 
('CX-5'), 
('CX-50'), 
('CX-7'), 
('CX-9'), 
('CX-90'), 
('GLC'), 
('Millenia'), 
('MPV'), 
('MX-3'), 
('MX-30'), 
('MX-5'), 
('MX-5 Miata'), 
('MX-6'), 
('Navajo'), 
('Protege'), 
('Protege/Protege 5'), 
('Protege/Protege MPS'), 
('RX-7'), 
('RX-8'), 
('Speed 3'), 
('Tribute'), 
('240 DL/240 GL Sedan'), 
('240 DL/240 GL Wagon'), 
('740 GLE Sedan'), 
('740 GLE Wagon'), 
('540C Coupe'), 
('570GT'), 
('570S Coupe'), 
('570S Spider'), 
('600LT Coupe'), 
('600LT Spider'), 
('620R Coupe'), 
('650S Can-Am'), 
('650S Coupe'), 
('650S Spider'), 
('675LT Coupe'), 
('675LT Spider'), 
('720S Coupe'), 
('720S Spider'), 
('765LT Coupe'), 
('765LT Spider'), 
('Artura'), 
('Elva'), 
('MP4-12C Coupe'), 
('MP4-12C Spider'), 
('MSO HS'), 
('P1'), 
('Sabre'), 
('Senna'), 
('Speedtail'), 
('190'), 
('230'), 
('260'), 
('350'), 
('380'), 
('400'), 
('420'), 
('560'), 
('A-Class'), 
('C-Class'), 
('CLA-Class'), 
('CLS-Class'), 
('E-Class'), 
('EQE'), 
('EQS'), 
('G-Class'), 
('GL-Class'), 
('GLA-Class'), 
('GLB-Class'), 
('GLC-Class'), 
('GLE-Class'), 
('GLS-Class'), 
('AMG GT'), 
('S-Class'), 
('SL-Class'), 
('SLC-Class'), 
('SLK-Class'), 
('B-Class Electric Drive'), 
('CL-Class'), 
('CLK-Class'), 
('EQB'), 
('GLK-Class'), 
('Maybach'), 
('Metris Cargo'), 
('Metris Passenger'), 
('ML-Class'), 
('R-Class'), 
('SLR'), 
('SLS AMG'), 
('Capri'), 
('Cougar'), 
('Grand Marquis'), 
('Lynx'), 
('Marauder'), 
('Mariner'), 
('Marquis'), 
('Milan'), 
('Montego'), 
('Monterey'), 
('Mountaineer'), 
('Mystique'), 
('Sable'), 
('Topaz'), 
('Tracer'), 
('Villager'), 
('Scorpio'), 
('XR4Ti'), 
('Clubman'), 
('Cooper'), 
('Countryman'), 
('Paceman'), 
('John Cooper Works'), 
('MiniE'), 
('3000 GT'), 
('3000 GT Spyder'), 
('Cordia'), 
('Diamante'), 
('Eclipse'), 
('Eclipse Cross'), 
('Endeavor'), 
('Expo'), 
('Galant'), 
('i-MiEV'), 
('Mirage'), 
('Montero'), 
('Montero Sport'), 
('Nativa'), 
('Outlander'), 
('Raider Pickup'), 
('Sigma'), 
('Space Wagon'), 
('Starion'), 
('Tredia'), 
('Truck'), 
('Van'), 
('MV-1'), 
('Plus Eight'), 
('200SX'), 
('240SX'), 
('300ZX'), 
('350z'), 
('370z'), 
('Altima'), 
('Altima / Stanza'), 
('Altra EV'), 
('ARIYA'), 
('Armada'), 
('Axxess'), 
('Cube'), 
('Frontier'), 
('GT-R'), 
('Hardbody'), 
('Hyper-Mini'), 
('Juke'), 
('Kicks'), 
('Leaf'), 
('Maxima'), 
('Murano'), 
('NV200 Cargo Van'), 
('NV200 NYC Taxi'), 
('Pathfinder'), 
('Pulsar NX'), 
('Pulsar/Pulsar-NX'), 
('Quest'), 
('Rogue'), 
('Rogue Sport'), 
('Sentra'), 
('Sentra/200SX'), 
('Stanza'), 
('Titan'), 
('Versa'), 
('Xterra'), 
('Z'), 
('Achieva'), 
('Alero'), 
('Bravada'), 
('Calais'), 
('Ciera'), 
('Custom Cruiser'), 
('Cutlass'), 
('Cutlass Calais'), 
('Cutlass Ciera'), 
('Cutlass Cruiser'), 
('Cutlass Supreme'), 
('Delta 88'), 
('Delta 88 Royale'), 
('Eighty-Eight'), 
('Eighty-Eight/Regency'), 
('Eighty-Eight/Regency/LSS'), 
('Firenza'), 
('Intrigue'), 
('Ninety-Eight'), 
('Ninety-Eight II'), 
('Ninety-Eight Regency'), 
('Ninety-Eight/Touring'), 
('Omega'), 
('Silhouette'), 
('Toronado'), 
('Trofeo/Toronado'), 
('Huayra'), 
('Huayra Coupe'), 
('Panoz Roadster'), 
('Kallista'), 
('Pas-Syclone'), 
('Pas-Typhoon'), 
('505'), 
('405'), 
('604'), 
('Acclaim'), 
('Breeze'), 
('Caravelle'), 
('Gran Fury'), 
('Horizon'), 
('Reliant'), 
('Sundance'), 
('Sundance/Duster'), 
('Turismo'), 
('Voyager/Grand Voyager'), 
('1'), 
('1000'), 
('6000'), 
('Sunbird'), 
('Firebird/Trans Am/Formula'), 
('Aztek'), 
('Bonneville'), 
('Fiero'), 
('Firefly'), 
('G3'), 
('G5'), 
('G6'), 
('G8'), 
('Grand Am'), 
('Grand Prix'), 
('GTO'), 
('Lemans'), 
('Montana'), 
('Parisienne'), 
('Phoenix'), 
('Solstice'), 
('Sunburst'), 
('Sunfire'), 
('Torrent'), 
('Trans Sport/Montana'), 
('Vibe'), 
('Wave'), 
('911'), 
('944'), 
('968'), 
('718'), 
('918 Spyder'), 
('924'), 
('928'), 
('Boxster'), 
('Carrera'), 
('Carrera 2 911 GT3'), 
('Carrera 2 Cabriolet'), 
('Carrera 2 Cabriolet Kit'), 
('Carrera 2 Coupe'), 
('Carrera 2 Coupe Kit'), 
('Carrera 2 S Cabriolet'), 
('Carrera 2 S Coupe'), 
('Carrera 4'), 
('Carrera 4 Cabriolet'), 
('Carrera 4 Cabriolet Kit'), 
('Carrera 4 Coupe'), 
('Carrera 4 S'), 
('Carrera 4 S Cabriolet'), 
('Carrera 4 S Cabriolet Kit'), 
('Carrera 4 S Coupe'), 
('Carrera 4 S Kit'), 
('Carrera 4 S Targa'), 
('Carrera 4 Targa'), 
('Carrera GT'), 
('Cayenne'), 
('Cayman'), 
('Macan'), 
('New 911 Carrera'), 
('Panamera'), 
('Targa'), 
('Taycan'), 
('Turbo'), 
('Turbo 2 911 GT2'), 
('Turbo 4 911'), 
('Turbo 4 911 Cab'), 
('Turbo 4 911 Cab Kit'), 
('Turbo 4 911 Kit'), 
('Turbo 4 911 S'), 
('Turbo 4 911 Turbo'), 
('Turbo 4 911 Turbo Cab S'), 
('Turbo GT2'), 
('Turbo Kit'), 
('Chevrolet Cavalier'), 
('Detomaso Mangusta'), 
('1500'), 
('C/V'), 
('Promaster City'), 
('Delta 204T'), 
('18i/Wagon/SportWagon'), 
('Alliance/Encore'), 
('Fuego'), 
('GTA'), 
('R1S'), 
('R1T'), 
('Brooklands/Turbo R'), 
('Camargue'), 
('Corniche/Continental'), 
('Cullinan'), 
('Dawn'), 
('Eight/Mulsan/Mulsanne'), 
('Ghost'), 
('Park Ward'), 
('Phantom'), 
('Silver Dawn'), 
('Silver Seraph'), 
('Silver Spirit II/Silver Spur'), 
('Silver Spirit III/Spur III'), 
('Silver Spirit/Silver Spur'), 
('Silver Spirit/Spur/Mulsanne'), 
('Silver Spur'), 
('Silver Spur II Mpw Touring L'), 
('Silver Spur III Limousine'), 
('Silver Spur Limousine'), 
('Silver Spur Park Ward'), 
('Silver Spur/Silver Dawn'), 
('Spirit III/Spur III/Dawn'), 
('Wraith'), 
('Stage 3 Mustang'), 
('RUF Turbo 12/CTR3'), 
('RUFTurbo12/CTR3/CTR2017'), 
('Turbo12/CTR3/CTR ANNIVERSARY'), 
('Ruf'), 
('900'), 
('9000'), 
('44994'), 
('45055'), 
('44966'), 
('45025'), 
('45116'), 
('Convertible'), 
('SSC'), 
('F150 Supercharged'), 
('S281 Family'), 
('S331 Family'), 
('Astra'), 
('Aura'), 
('Ion'), 
('L100/200'), 
('L300'), 
('LW'), 
('Outlook'), 
('Relay'), 
('SKY'), 
('SL'), 
('SW'), 
('Vue'), 
('FR-S'), 
('iA'), 
('iM'), 
('iQ'), 
('xA'), 
('xB'), 
('xD'), 
('Mustang GT'), 
('fortwo'), 
('C8'), 
('825'), 
('827'), 
('S209'), 
('Ascent'), 
('Tribeca'), 
('Baja'), 
('Brat'), 
('BRZ'), 
('Crosstrek'), 
('Forester'), 
('HaTChback'), 
('Impreza/Outback Sport'), 
('Impreza'), 
('Justy'), 
('Legacy/Outback'), 
('Legacy'), 
('Loyale'), 
('Outback'), 
('RX Turbo'), 
('Solterra'), 
('SVX'), 
('WRX'), 
('XT'), 
('Aerio'), 
('Equator'), 
('Esteem'), 
('Forenza'), 
('Forsa'), 
('Grand Vitara'), 
('Kizashi'), 
('Reno'), 
('SA 310'), 
('Samurai'), 
('Sidekick'), 
('SJ 410'), 
('Swift'), 
('SX4'), 
('Verona'), 
('Vitara'), 
('X-90'), 
('XL7'), 
('Foose F150'), 
('Model 3'), 
('Model S'), 
('Model X'), 
('Model Y'), 
('500SEC'), 
('500SE'), 
('500SEL'), 
('500SL'), 
('86'), 
('Truck/T100'), 
('4Runner'), 
('Avalon'), 
('bZ4X'), 
('Cab Chassis'), 
('Camry'), 
('Celica'), 
('C-HR'), 
('Corolla'), 
('Corolla Cross'), 
('Cressida'), 
('Crown'), 
('Echo'), 
('FJ Cruiser'), 
('GR 86'), 
('GR Supra'), 
('Grand Highlander'), 
('Highlander'), 
('Land Cruiser'), 
('Matrix'), 
('MR2'), 
('Paseo'), 
('Previa'), 
('Prius'), 
('Prius c'), 
('Prius Prime'), 
('Prius v'), 
('RAV4'), 
('RAV4 Prime'), 
('Sequoia'), 
('Sienna'), 
('Starlet'), 
('Supra'), 
('Tacoma'), 
('Tercel'), 
('Tundra'), 
('Venza'), 
('Yaris'), 
('TVR 280i Convertible'), 
('TVR 280i Coupe'), 
('TVR 280i/350i Convertible'), 
('TVR 280i/350i Coupe'), 
('Avtech SC / M12'), 
('W8'), 
('VF 8'), 
('21 TD'), 
('Niva'), 
('Arteon'), 
('Atlas'), 
('Beetle'), 
('Cabrio'), 
('CC'), 
('Corrado'), 
('Golf/GTI'), 
('Eos'), 
('Eurovan'), 
('Fox'), 
('GLI'), 
('ID.4'), 
('Jetta'), 
('Passat'), 
('Quantum'), 
('R32'), 
('Rabbit'), 
('Routan'), 
('Scirocco'), 
('Taos'), 
('Tiguan'), 
('Touareg'), 
('Vanagon'), 
('240'), 
('740/760'), 
('780'), 
('850'), 
('940'), 
('960'), 
('960 Wagon/V90'), 
('960/S90'), 
('C30'), 
('C40'), 
('C70'), 
('S40'), 
('S60'), 
('S70'), 
('S80'), 
('S90'), 
('V40'), 
('V50'), 
('V60'), 
('V70'), 
('V70 XC'), 
('V90'), 
('XC40'), 
('XC60'), 
('XC70'), 
('XC90'), 
('Wetl 190E'), 
('Wetl 300'), 
('Wetl 412'), 
('Wetl 500'), 
('Wetl 560'), 
('Wetl 600 SEL'), 
('Wetl 850I'), 
('Wetl Testarossa'), 
('GV/GVX'), 
('GV Plus/GV/Cabrio'), 
('Gy/yugo GVX');