INSERT INTO VehicleBaseModels (BaseModel)
VALUES
('CL'), 
('TL'), 
('RL'), 
('ILX'), 
('Integra'), 
('Legend'), 
('MDX'), 
('NSX'), 
('RDX'), 
('RLX'), 
('RSX'), 
('SLX'), 
('TLX'), 
('TSX'), 
('Vigor'), 
('ZDX'), 
('164'), 
('4C'), 
('Spider'), 
('Giulia'), 
('GT'), 
('GTV'), 
('Milano'), 
('Stelvio'), 
('DJ Po Vehicle'), 
('FJ8c Post Office'), 
('Post Office DJ5'), 
('Post Office DJ8'), 
('Eagle'), 
('GNX'), 
('DB AR1'), 
('DB11'), 
('DB7'), 
('DB-7 GT'), 
('DB-7 Vantage'), 
('DB9'), 
('DBS'), 
('DBX 707'), 
('DBX V8'), 
('Lagonda'), 
('Rapide'), 
('Saloon/Vantage/Volante'), 
('Vanquish'), 
('Vantage'), 
('Vantage Manual'), 
('Virage'), 
('Virage/Volante'), 
('80/90'), 
('100'), 
('200'), 
('4000'), 
('5000'), 
('A3'), 
('A4'), 
('A5'), 
('A6'), 
('A7'), 
('A8'), 
('Allroad'), 
('Cabriolet'), 
('Coupe GT'), 
('Coupe quattro'), 
('e-tron'), 
('e-tron GT'), 
('e-tron S'), 
('Q3'), 
('Q4 e-tron'), 
('Q5'), 
('Q7'), 
('Q8'), 
('Q8 e-tron'), 
('Quattro'), 
('R8'), 
('R8 Spyder'), 
('RS 3'), 
('RS'), 
('RS 5'), 
('RS 7'), 
('RS e-tron GT'), 
('RS Q8'), 
('RS 4'), 
('RS 6'), 
('S3'), 
('S4'), 
('S5'), 
('S6'), 
('S7'), 
('S8'), 
('SQ5'), 
('SQ7'), 
('SQ8'), 
('TT Coupe'), 
('TT'), 
('TT Roadster'), 
('TT RS'), 
('TTS Coupe'), 
('TTS'), 
('V8'), 
('Aurora'), 
('A.C.MARK IV'), 
('A.C.Mkiv'), 
('Avanti II'), 
('Transit Connect Electric Van/Wagon'), 
('Arnage'), 
('Azure'), 
('Bentayga'), 
('Brooklands'), 
('Continental Flying Spur'), 
('Continental'), 
('Continental GT Convertible'), 
('Continental Supersports'), 
('Continental Supersports Convertible'), 
('Flying Spur'), 
('Mulsanne'), 
('Turbo RT'), 
('X1/9'), 
('Dovell 230CE'), 
('Dovell 230E'), 
('Bitter SC'), 
('SC'), 
('1 Series'), 
('2 Series'), 
('3 Series'), 
('4 Series'), 
('5 Series'), 
('6 Series'), 
('7 Series'), 
('8 Series'), 
('Active E'), 
('ActiveHybrid X6'), 
('X7'), 
('i3'), 
('i4'), 
('i5'), 
('i7'), 
('i8'), 
('iX'), 
('M'), 
('X1'), 
('X2'), 
('X3'), 
('X4'), 
('X5'), 
('X6'), 
('XM'), 
('Z3'), 
('Z4'), 
('Z8'), 
('Roadster'), 
('Chiron'), 
('Divo'), 
('Veyron'), 
('Cascada'), 
('Century'), 
('Century Estate Wagon'), 
('Century Wagon'), 
('Coachbuilder Wagon'), 
('Electra Estate Wagon'), 
('Electra/Park Avenue'), 
('Enclave'), 
('Encore'), 
('Envision'), 
('Envista'), 
('Estate Wagon'), 
('Funeral Coach/Hearse'), 
('LaCrosse'), 
('Lacrosse/Allure'), 
('LeSabre'), 
('LeSabre/Electra Wagon'), 
('Lucerne'), 
('Park Avenue'), 
('Rainier'), 
('Reatta'), 
('Regal'), 
('Regal/Century'), 
('Rendezvous'), 
('Riviera'), 
('Roadmaster'), 
('Skyhawk'), 
('Skylark'), 
('Somerset Regal'), 
('Somerset/Skylark'), 
('Terraza'), 
('Verano'), 
('e6'), 
('Allante'), 
('Armored Deville'), 
('Armored DTS'), 
('ATS'), 
('ATS-V'), 
('Brougham'), 
('Brougham/DeVille'), 
('Catera'), 
('Cimarron'), 
('Commercial Chassis'), 
('CT4'), 
('CT5'), 
('CT6'), 
('CTS'), 
('CTS-V'), 
('DeVille'), 
('DeVille/60 Special'), 
('DeVille/Concourse'), 
('DTS'), 
('Eldorado'), 
('ELR'), 
('Escalade'), 
('Fleetwood'), 
('Fleetwood Brougham'), 
('Fleetwood/DeVille'), 
('Limousine'), 
('LYRIQ'), 
('Seville'), 
('SRX'), 
('STS'), 
('STS-V'), 
('XLR'), 
('XLR-V'), 
('XT4'), 
('XT5'), 
('XT6'), 
('XTS'), 
('XTS Hearse'), 
('XTS Limo'), 
('Duntov GT'), 
('Astro Cargo'), 
('Astro Passenger'), 
('Avalanche'), 
('Aveo'), 
('Beretta'), 
('Blazer'), 
('Bolt EUV'), 
('Bolt EV'), 
('C10 Pickup'), 
('C1500 Pickup'), 
('C20 Pickup'), 
('C2500 Pickup'), 
('Camaro'), 
('Caprice'), 
('Impala/Caprice'), 
('Captiva'), 
('Cavalier'), 
('Celebrity'), 
('Chevette'), 
('Citation II'), 
('City Express Cargo Van'), 
('Classic'), 
('Cobalt'), 
('Colorado'), 
('Corsica'), 
('Corvette'), 
('Cruze'), 
('El Camino Pickup'), 
('Epica'), 
('Equinox'), 
('Express Cargo'), 
('Express Passenger'), 
('G10/20 Van'), 
('Sport Van'), 
('G30 Van'), 
('HHR'), 
('Impala'), 
('K10 Pickup'), 
('K1500 Pickup'), 
('K20 Pickup'), 
('K2500 Pickup'), 
('Lumina'), 
('Lumina Minivan'), 
('Lumina/APV Minivan'), 
('Lumina/Monte Carlo'), 
('Malibu'), 
('Metro'), 
('Monte Carlo'), 
('Nova'), 
('Optra'), 
('Pickup 2500'), 
('Postal Cab Chassis'), 
('Prizm'), 
('R10 Pickup'), 
('Suburban'), 
('R20 (C20) Pickup'), 
('S10 Cab Chassis'), 
('S10 Pickup'), 
('S10 Utility Body'), 
('Silverado'), 
('Sonic'), 
('Spark'), 
('Spectrum'), 
('Sprint'), 
('SS'), 
('SSR Pickup'), 
('T10 (S10) Pickup'), 
('Tahoe'), 
('Tracker'), 
('Trailblazer'), 
('Traverse'), 
('Trax'), 
('Uplander'), 
('V10 (K10) Pickup'), 
('V20 Pickup'), 
('Van 15/25 Conversion'), 
('Van 1500'), 
('Van 1500/2500'), 
('Venture'), 
('Volt'), 
('300'), 
('300 SRT8'), 
('Aspen'), 
('Cirrus'), 
('Concorde'), 
('Concorde/LHS'), 
('Conquest'), 
('Crossfire'), 
('E Class/New Yorker'), 
('Executive Sedan/Limousine'), 
('Fifth Avenue/Imperial'), 
('Imperial/New Yorker Fifth Avenue'), 
('JX/JXI/Limited Convertible'), 
('Laser'), 
('Laser/Daytona'), 
('LeBaron'), 
('LHS'), 
('New Yorker'), 
('New Yorker Fifth Avenue/Imperial'), 
('New Yorker/5th Avenue'), 
('New Yorker/LHS'), 
('Newport/Fifth Avenue'), 
('Pacifica'), 
('Prowler'), 
('PT Cruiser'), 
('QC Car'), 
('Sebring'), 
('TC'), 
('Town and Country'), 
('Town and Country/Voyager/Grand Voyager'), 
('Voyager'), 
('Voyager/Town and Country'), 
('CODA'), 
('Consulier GTP'), 
('CX'), 
('Cxestate'), 
('WB'), 
('Coupe'), 
('Sedan'), 
('Station Wagon'), 
('Kalos'), 
('Lacetti'), 
('Lanos'), 
('Leganza'), 
('Magnus'), 
('Nubira'), 
('Charade'), 
('Rocky'), 
('600'), 
('Ramcharger'), 
('Aries'), 
('Avenger'), 
('B150/B250 Van'), 
('B150/B250 Wagon'), 
('B1500 Van'), 
('B1500 Wagon'), 
('B1500/B2500 Van'), 
('B1500/B2500 Wagon'), 
('B2500 Van'), 
('B2500 Wagon'), 
('B350 Van'), 
('B350 Wagon'), 
('B3500 Van'), 
('B3500 Wagon'), 
('Caliber'), 
('Caravan C/V/Grand Caravan'), 
('Caravan/Grand Caravan'), 
('Caravan/Grand Caravan/Ram Van'), 
('Caravan/Ram Van'), 
('Challenger'), 
('Charger'), 
('Colt'), 
('CSX'), 
('D100/D150 Pickup'), 
('D250 Cab Chassis'), 
('D250 Pickup'), 
('D250 Pickup Cab Chassis'), 
('Dakota Cab Chassis'), 
('Dakota Pickup'), 
('Dart'), 
('Daytona'), 
('Diplomat'), 
('Durango'), 
('Dynasty'), 
('GLH-S'), 
('Grand Caravan'), 
('Hornet'), 
('Intrepid'), 
('Journey'), 
('Lancer'), 
('Magnum'), 
('Monaco'), 
('Neon'), 
('Neon/SRT-4/SX 2.0'), 
('Nitro'), 
('Omni'), 
('Power Ram 50 Pickup'), 
('Raider'), 
('Ram 1500 Pickup'), 
('Ram 2500 Pickup'), 
('Ram 50 Pickup'), 
('Ram Van 1500'), 
('Ram Van 2500'), 
('Ram Wagon 1500'), 
('Ram Wagon 2500'), 
('Rampage Pickup'), 
('Shadow'), 
('Spirit'), 
('Stealth'), 
('Stratus'), 
('Viper'), 
('W100/W150 Pickup'), 
('W250 Pickup'), 
('Funeral Coach'), 
('Medallion'), 
('Premier'), 
('Renault Medallion'), 
('Summit'), 
('Talon'), 
('Vision'), 
('Wagon'), 
('ERD 1'), 
('Series 1'), 
('Phaeton'), 
('24E'), 
('85J'), 
('Formal'), 
('Heritage'), 
('Lincoln 100J'), 
('Lincoln 24E'), 
('Lincoln 85J'), 
('Lincoln Eagle/Windsor'), 
('Lincoln Eaton'), 
('Lincoln Stratford'), 
('Renaissance'), 
('Six Door'), 
('Windsor'), 
('308'), 
('575'), 
('296 GTB'), 
('3.2 Mondial/Cabriolet'), 
('328 GTS/GTB'), 
('348 TB/TS'), 
('360 Modena/Modena F1'), 
('360 Modena/Spider'), 
('360 Modena/Spider/Challenge'), 
('456 MGT/MGA'), 
('458 Italia'), 
('458 Speciale'), 
('458 Spider'), 
('488 GTB'), 
('488 Pista'), 
('488 Pista Spider'), 
('488 Spider'), 
('550 Maranello'), 
('550 Maranello/Barchetta'), 
('575 M Maranello'), 
('575 M Maranello and Superamerica'), 
('599 GTB'), 
('599 GTB Fiorano'), 
('599 GTO'), 
('599 SA Aperta'), 
('612 Scaglietti'), 
('812 Competizione'), 
('812 GTS'), 
('812 Superfast'), 
('California'), 
('California T'), 
('Daytona SP3'), 
('Enzo Ferrari'), 
('F 40'), 
('F12'), 
('F12 Berlinetta'), 
('F12 tdf'), 
('F141'), 
('F355/355 F1'), 
('F40'), 
('F430'), 
('F60 America'), 
('F8 Spider'), 
('F8 Tributo'), 
('Ferrari 348 TB/TS'), 
('Ferrari 348 TB/TS/Spider'), 
('Ferrari 456'), 
('Ferrari 512 TR'), 
('Ferrari 550 Maranello'), 
('Ferrari F355'), 
('Ferrari F355 Berlinetta/GTS'), 
('Ferrari F355/355 F1'), 
('Ferrari F50'), 
('Ferrari F512M'), 
('Ferrari Mondial T/Cabriolet'), 
('FF'), 
('GTC4Lusso'), 
('LaFerrari'), 
('Mondial'), 
('Mondial T/Cabriolet'), 
('Mondial/Cabriolet'), 
('Monza SP1'), 
('Monza SP2'), 
('Portofino'), 
('Roma'), 
('SF90 Spider'), 
('SF90 Stradale'), 
('SF90 Stradale Coupe'), 
('Testarossa'), 
('500'), 
('124 Spider'), 
('500 L'), 
('500 X'), 
('500e'), 
('Karma'), 
('Ocean'), 
('Aerostar Van'), 
('Aerostar Wagon'), 
('Aspire'), 
('Bronco'), 
('Bronco II'), 
('Bronco Sport'), 
('C-MAX'), 
('Contour'), 
('Courier'), 
('Crown Victoria'), 
('E150 Club Wagon'), 
('E150 Econoline'), 
('E150 Van'), 
('E150 Wagon'), 
('E250 Van'), 
('E250 Econoline'), 
('E350 Van'), 
('E350 Wagon'), 
('EcoSport'), 
('Edge'), 
('Escape'), 
('Escort'), 
('EXP'), 
('Expedition'), 
('Explorer'), 
('F150'), 
('F-150 Lightning'), 
('F250'), 
('Festiva'), 
('Fiesta'), 
('Five Hundred'), 
('Flex'), 
('Focus'), 
('Freestar'), 
('Freestyle'), 
('Fusion'), 
('LTD'), 
('LTD Crown Victoria'), 
('LTD Crown Victoria/Country Squire Wagon'), 
('Maverick'), 
('Mustang'), 
('Mustang Mach-E'), 
('Postal Vehicle'), 
('Probe'), 
('Ranger'), 
('Taurus'), 
('Tempo'), 
('Th!nk'), 
('Thunderbird'), 
('Transit Connect'), 
('Transit T150 Wagon'), 
('Windstar'), 
('G80'), 
('GV70'), 
('G70'), 
('G90'), 
('GV60'), 
('GV80'), 
('Storm'), 
('Acadia'), 
('Pickup'), 
('C2500 Sierra'), 
('Caballero Pickup'), 
('Canyon'), 
('Envoy'), 
('EV1'), 
('Rally'), 
('Vandura'), 
('Hummer EV'), 
('Jimmy'), 
('K2500 Sierra'), 
('S15 Cab Chassis'), 
('S15 Pickup'), 
('S15 Utility Body'), 
('Safari'), 
('Safari Cargo'), 
('Safari Passenger'), 
('Savana Cargo'), 
('Savana Passenger'), 
('Sierra'), 
('Sonoma'), 
('Terrain'), 
('Yukon'), 
('Goldacre Limited'), 
('LLV'), 
('Kubvan'), 
('Accord'), 
('Crosstour'), 
('Civic'), 
('Del Sol'), 
('Clarity'), 
('CR-V'), 
('CR-Z'), 
('Element'), 
('EV Plus'), 
('Fit'), 
('HR-V'), 
('Insight'), 
('Odyssey'), 
('Passport'), 
('Pilot'), 
('Prelude'), 
('Ridgeline'), 
('S2000'), 
('H3'), 
('H3T'), 
('Accent'), 
('Accent/Brio'), 
('Azera'), 
('Elantra'), 
('Entourage'), 
('Equus'), 
('Excel'), 
('Genesis'), 
('Ioniq'), 
('Ioniq 5'), 
('Ioniq 6'), 
('J-Car/Elantra'), 
('Kona'), 
('Palisade'), 
('Pony Excel'), 
('Precis'), 
('Santa Cruz'), 
('Santa Fe'), 
('Scoupe'), 
('Sonata'), 
('Tiburon'), 
('Tucson'), 
('Veloster'), 
('Venue'), 
('Veracruz'), 
('XG'), 
('EX35'), 
('EX37'), 
('FX35'), 
('FX37'), 
('FX45'), 
('FX50'), 
('G20'), 
('G25'), 
('G35'), 
('G37'), 
('I30'), 
('I35'), 
('J30'), 
('JX35'), 
('M30'), 
('M35'), 
('M37'), 
('M45'), 
('M56'), 
('Q40'), 
('Q45'), 
('Q50'), 
('Q60'), 
('Q70'), 
('QX30'), 
('QX4'), 
('QX50'), 
('QX55'), 
('QX56'), 
('QX60'), 
('QX70'), 
('QX80'), 
('750C/I-Mark'), 
('Amigo'), 
('Ascender'), 
('Axiom'), 
('Hombre Pickup');