INSERT INTO VehicleModels (Model)
VALUES
('Yukon C1500 2WD'), 
('Yukon C1500 XL 2WD'), 
('Yukon Denali 1500 AWD'), 
('Yukon Denali 1500 Hybrid 4WD'), 
('Yukon Denali K10 AWD'), 
('Yukon Denali XL 1500 AWD'), 
('Yukon K10 4WD'), 
('Yukon K1500 4WD'), 
('Yukon K1500 XL 4WD'), 
('Yukon XL 1500 2WD'), 
('Yukon XL 1500 4WD'), 
('Yukon XL 1500 AWD'), 
('Yukon XL 2500 2WD'), 
('Yukon XL 2500 4WD'), 
('Yukon XL 2WD'), 
('Yukon XL 4WD'), 
('Yukon XL C10 2WD'), 
('Yukon XL K10 4WD'), 
('Yukon XL K10 AWD'), 
('Goldacre Limited'), 
('LLV'), 
('Kubvan'), 
('Accord'), 
('Accord 2.0T Sport/Touring'), 
('Accord Coupe'), 
('Accord Crosstour 2WD'), 
('Accord Crosstour 4WD'), 
('Accord Hybrid'), 
('Accord Hybrid Sport/Touring'), 
('Accord Plug-in Hybrid'), 
('Accord Sport/Touring'), 
('Accord Wagon'), 
('Civic'), 
('Civic 2Dr'), 
('Civic 4Dr'), 
('Civic 5Dr'), 
('Civic 5Dr - Type R'), 
('Civic 5Dr Sport'), 
('Civic CNG'), 
('Civic CRX'), 
('Civic CRX HF'), 
('Civic Del Sol'), 
('Civic HB VX'), 
('Civic HF'), 
('Civic HX'), 
('Civic Hybrid'), 
('Civic Natural Gas'), 
('Civic Si 2Dr'), 
('Civic Si 4Dr'), 
('Civic Wagon'), 
('Civic Wagon 4WD'), 
('Clarity EV'), 
('Clarity Plug-in Hybrid'), 
('Crosstour 2WD'), 
('Crosstour 4WD'), 
('CR-V 2WD'), 
('CR-V 4WD'), 
('CR-V AWD'), 
('CR-V FWD'), 
('CR-V Hybrid AWD'), 
('CR-V Hybrid FWD'), 
('CR-Z'), 
('Del Sol'), 
('Element 2WD'), 
('Element 4WD'), 
('EV Plus'), 
('Fit'), 
('Fit EV'), 
('HR-V 2WD'), 
('HR-V 4WD'), 
('HR-V AWD'), 
('HR-V FWD'), 
('Insight'), 
('Insight Touring'), 
('Odyssey'), 
('Passport 2WD'), 
('Passport 4WD'), 
('Passport AWD'), 
('Passport FWD'), 
('Pilot 2WD'), 
('Pilot 4WD'), 
('Pilot AWD'), 
('Pilot AWD Touring/Elite/Black'), 
('Pilot AWD TrailSport'), 
('Pilot FWD'), 
('Prelude'), 
('Ridgeline AWD'), 
('Ridgeline FWD'), 
('Ridgeline Truck 4WD'), 
('S2000'), 
('H3 4WD'), 
('H3T 4WD'), 
('Accent'), 
('Accent (SOHC)'), 
('Accent (Sporty)'), 
('Accent Blue'), 
('Accent/Brio'), 
('Azera'), 
('Azera Limited'), 
('Elantra'), 
('Elantra Blue'), 
('Elantra Coupe'), 
('Elantra GT'), 
('Elantra HaTChback'), 
('Elantra Hybrid'), 
('Elantra Hybrid Blue'), 
('Elantra Limited'), 
('Elantra N'), 
('Elantra SE'), 
('Elantra Touring'), 
('Elantra Wagon'), 
('Entourage'), 
('Equus'), 
('Excel'), 
('Genesis'), 
('Genesis AWD'), 
('Genesis Coupe'), 
('Genesis R Spec'), 
('Genesis R-Spec'), 
('Genesis RWD'), 
('Ioniq'), 
('Ioniq 5 AWD (Long Range)'), 
('Ioniq 5 Long range AWD'), 
('Ioniq 5 Long range RWD'), 
('Ioniq 5 RWD (Long Range)'), 
('Ioniq 5 RWD (Standard Range)'), 
('Ioniq 5 Standard range RWD'), 
('Ioniq 6 Long range AWD'), 
('Ioniq 6 Long range RWD'), 
('Ioniq 6 Standard Range RWD'), 
('Ioniq Blue'), 
('Ioniq Electric'), 
('Ioniq Plug-in Hybrid'), 
('J-Car/Elantra'), 
('Kona AWD'), 
('Kona Electric'), 
('Kona FWD'), 
('Kona N'), 
('Palisade AWD'), 
('Palisade FWD'), 
('Pony Excel'), 
('Precis'), 
('Santa Cruz AWD'), 
('Santa Cruz FWD'), 
('Santa Fe 2WD'), 
('Santa Fe 4WD'), 
('Santa Fe AWD'), 
('Santa Fe FWD'), 
('Santa Fe Hybrid'), 
('Santa Fe Hybrid Blue'), 
('Santa Fe Plug-in Hybrid'), 
('Santa Fe Sport 2WD'), 
('Santa Fe Sport 4WD'), 
('Santa Fe Sport AWD'), 
('Santa Fe Sport FWD'), 
('Santa Fe Sport Ultimate AWD'), 
('Santa Fe Sport Ultimate FWD'), 
('Santa Fe Ultimate 2WD'), 
('Santa Fe Ultimate 4WD'), 
('Santa Fe Ultimate AWD'), 
('Santa Fe Ultimate FWD'), 
('Santa Fe XL AWD'), 
('Santa Fe XL FWD'), 
('Santa Fe XL Ultimate AWD'), 
('Santa Fe XL Ultimate FWD'), 
('Scoupe'), 
('Sonata'), 
('Sonata (Y-3)'), 
('Sonata Hybrid'), 
('Sonata Hybrid Blue'), 
('Sonata Hybrid Limited'), 
('Sonata Hybrid SE'), 
('Sonata Limited'), 
('Sonata Plug-in Hybrid'), 
('Sonata SE'), 
('Sonata Sport Limited'), 
('Tiburon'), 
('Tiburon (Coupe)'), 
('Tucson 2WD'), 
('Tucson 4WD'), 
('Tucson AWD'), 
('Tucson Eco AWD'), 
('Tucson Eco FWD'), 
('Tucson FWD'), 
('Tucson Hybrid'), 
('Tucson Hybrid Blue'), 
('Tucson Plug-in Hybrid'), 
('Veloster'), 
('Veloster N'), 
('Venue'), 
('Veracruz 2WD'), 
('Veracruz 4WD'), 
('XG300'), 
('XG350'), 
('EX35'), 
('EX35 AWD'), 
('EX37'), 
('EX37 AWD'), 
('FX35 2WD'), 
('FX35 AWD'), 
('FX35 RWD'), 
('FX37 AWD'), 
('FX37 RWD'), 
('FX45 AWD'), 
('FX50'), 
('FX50 AWD'), 
('G20'), 
('G25'), 
('G25x'), 
('G35'), 
('G35 Coupe'), 
('G35x'), 
('G37'), 
('G37 Convertible'), 
('G37 Coupe'), 
('G37x'), 
('G37x Coupe'), 
('I30'), 
('I35'), 
('J30'), 
('JX35 AWD'), 
('JX35 FWD'), 
('M30'), 
('M35'), 
('M35h'), 
('M35x'), 
('M37'), 
('M37x'), 
('M45'), 
('M45x'), 
('M56'), 
('M56x'), 
('Q40'), 
('Q40 AWD'), 
('Q45'), 
('Q45 Full-Active Suspension'), 
('Q45 Sport'), 
('Q50'), 
('Q50 AWD'), 
('Q50 Hybrid'), 
('Q50 Hybrid AWD'), 
('Q50 Red Sport'), 
('Q50 Red Sport  AWD'), 
('Q50a'), 
('Q50a AWD'), 
('Q50S'), 
('Q50S AWD'), 
('Q50S Hybrid'), 
('Q50S Hybrid AWD'), 
('Q50S Red Sport'), 
('Q50S Red Sport  AWD'), 
('Q60'), 
('Q60 AWD'), 
('Q60 AWD Coupe'), 
('Q60 Convertible'), 
('Q60 Coupe'), 
('Q60 Red Sport'), 
('Q60 Red Sport AWD'), 
('Q60S Red Sport'), 
('Q60S Red Sport AWD'), 
('Q70'), 
('Q70 AWD'), 
('Q70 Hybrid'), 
('QX30'), 
('QX30 AWD'), 
('QX4 2WD'), 
('QX4 4WD'), 
('QX50'), 
('QX50 AWD'), 
('QX55 AWD'), 
('QX56 2WD'), 
('QX56 4WD'), 
('QX60 AWD'), 
('QX60 FWD'), 
('QX60 Hybrid AWD'), 
('QX60 Hybrid FWD'), 
('QX70 AWD'), 
('QX70 RWD'), 
('QX80 2WD'), 
('QX80 4WD'), 
('750C/I-Mark'), 
('Amigo 2WD'), 
('Amigo 4WD'), 
('Ascender 2WD'), 
('Ascender 4WD'), 
('Ascender 5-Passenger 2WD'), 
('Ascender 5-Passenger 4WD'), 
('Ascender 7-Passenger 2WD'), 
('Ascender 7-Passenger 4WD'), 
('Axiom 2WD'), 
('Axiom 4WD'), 
('Hombre Pickup 2WD'), 
('Hombre Pickup 2WD (FFV)'), 
('Hombre Pickup 4WD'), 
('i-280 Extended Cab 2WD'), 
('i-290 Extended Cab 2WD'), 
('i-350 Crew Cab 4WD'), 
('i-370 Crew Cab 2WD'), 
('i-370 Crew Cab 4WD'), 
('i-370 Extended Cab 2WD'), 
('I-Mark'), 
('Impulse'), 
('Oasis'), 
('Pickup 2WD'), 
('Pickup 2WD 1-Ton'), 
('Pickup 4WD'), 
('Rodeo 2WD'), 
('Rodeo 4WD'), 
('Rodeo Sport 2WD'), 
('Rodeo Sport 4WD'), 
('Stylus'), 
('Trooper'), 
('Trooper 2WD'), 
('Trooper 4WD'), 
('Vehicross'), 
('Vehicross 4WD'), 
('E-Pace'), 
('E-Pace (296 Hp)'), 
('E-Pace MHEV'), 
('E-Pace P250'), 
('E-Pace P300'), 
('F-Pace'), 
('F-Pace (296 Hp)'), 
('F-Pace 30t'), 
('F-Pace P340 MHEV'), 
('F-Pace P400 MHEV'), 
('F-Pace SVR'), 
('F-Type AWD Convertible'), 
('F-Type AWD Coupe'), 
('F-Type Convertible'), 
('F-Type Coupe'), 
('F-Type P450 AWD R-Dynamic Convertible'), 
('F-Type P450 AWD R-Dynamic Coupe'), 
('F-Type P450 RWD Convertible'), 
('F-Type P450 RWD Coupe'), 
('F-Type R AWD Convertible'), 
('F-Type R AWD Coupe'), 
('F-Type R Convertible'), 
('F-Type R Coupe'), 
('F-Type S AWD Convertible'), 
('F-Type S AWD Coupe'), 
('F-Type S Convertible'), 
('F-Type S Coupe'), 
('F-Type SVR AWD Convertible'), 
('F-Type SVR AWD Convertible GEN2'), 
('F-Type SVR AWD Coupe'), 
('F-Type SVR AWD Coupe GEN2'), 
('F-Type V8 S Convertible'), 
('I-Pace'), 
('I-Pace EV400'), 
('I-Pace EV400 (20 inch tires)'), 
('I-Pace EV400 (22 inch tires)'), 
('S-Type'), 
('S-Type (X200) V6'), 
('S-Type (X200) V8'), 
('S-Type 3.0 Litre'), 
('S-Type 4.2 Litre'), 
('S-Type R'), 
('Super V8'), 
('Vanden Plas'), 
('Vanden Plas S.C.'), 
('Vdp'), 
('Vdp Lwb'), 
('XE'), 
('XE AWD'), 
('XE P250'), 
('XE P250 AWD'), 
('XE P300 AWD'), 
('XF'), 
('XF AWD'), 
('XF FFV'), 
('XF P250'), 
('XF P250 AWD'), 
('XF P300 AWD'), 
('XF Sportbrake AWD'), 
('XF Supercharged'), 
('XJ'), 
('XJ AWD'), 
('XJ FFV'), 
('XJ LWB'), 
('XJ LWB AWD'), 
('XJ Sport'), 
('XJ12'), 
('XJ6'), 
('XJ6L'), 
('XJ8'), 
('XJ8L'), 
('XJL'), 
('XJL AWD'), 
('XJL FFV'), 
('XJR'), 
('XJRS Convertble'), 
('XJRS Coupe'), 
('XJS'), 
('XJ-S'), 
('XJS Convertible'), 
('XJS Coupe'), 
('XJS V12 Convertible'), 
('XJS V12 Coupe'), 
('XJ-SC'), 
('XK'), 
('XK Convertible'), 
('XK8'), 
('XK8 Convertible'), 
('XKR'), 
('XKR Convertible'), 
('X-Type'), 
('X-Type Sport Brake'), 
('W-126/4 Series'), 
('Cherokee 2WD'), 
('Cherokee 4WD'), 
('Cherokee 4WD Active Drive II'), 
('Cherokee FWD'), 
('Cherokee Trailhawk 4WD'), 
('Cherokee/Wagoneer'), 
('Cherokee/Wagoneer 2WD'), 
('Cherokee/Wagoneer 4WD'), 
('CJ7'), 
('CJ7 4WD'), 
('CJ8 4WD'), 
('Comanche 2WD'), 
('Comanche 4WD'), 
('Comanche Pickup 2WD'), 
('Comanche Pickup 4WD'), 
('Commander 2WD'), 
('Commander 4WD'), 
('Compass 2WD'), 
('Compass 4WD'), 
('Compass FWD'), 
('Gladiator 4WD'), 
('Gladiator EcoDiesel 4WD'), 
('Gladiator Pickup 4WD'), 
('Gladiator Rubic EcoDiesel 4WD'), 
('Gladiator Rubicon EcoDiesel 4WD'), 
('Grand Cherokee 2WD'), 
('Grand Cherokee 4WD'), 
('Grand Cherokee 4xe'), 
('Grand Cherokee L 2WD'), 
('Grand Cherokee L 4WD'), 
('Grand Cherokee SRT 4WD'), 
('Grand Cherokee SRT8'), 
('Grand Cherokee SRT8 4WD'), 
('Grand Cherokee SRT8 AWD'), 
('Grand Cherokee TrackHawk 4WD'), 
('Grand Cherokee WK 2WD'), 
('Grand Cherokee WK 4WD'), 
('Grand Wagoneer'), 
('Grand Wagoneer 2WD'), 
('Grand Wagoneer 4WD'), 
('Grand Wagoneer L 4WD'), 
('J-10 Pickup 4WD'), 
('J-10 Pickup Truck'), 
('J-10 Pickup Truck 4WD'), 
('J-20 Pickup Truck'), 
('J-20 Pickup Truck 4WD'), 
('Liberty 2WD'), 
('Liberty 4WD'), 
('Liberty/Cherokee 2WD'), 
('Liberty/Cherokee 4WD'), 
('New Compass 2WD'), 
('New Compass 4WD'), 
('New Wrangler 4WD'), 
('New Wrangler Unlimited 4WD'), 
('Patriot 2WD'), 
('Patriot 4WD'), 
('Patriot FWD'), 
('Renegade 2WD'), 
('Renegade 4WD'), 
('Renegade Trailhawk 4WD'), 
('Scrambler'), 
('Scrambler Pickup 4WD'), 
('Wagoneer 2WD'), 
('Wagoneer 4WD'), 
('Wagoneer L 2WD'), 
('Wagoneer L 4WD'), 
('Wagoneer Limited 4WD'), 
('Wrangler 2dr 4WD'), 
('Wrangler 2WD'), 
('Wrangler 4dr 4WD'), 
('Wrangler 4dr 4xe'), 
('Wrangler 4dr EcoDiesel 4WD'), 
('Wrangler 4WD'), 
('Wrangler Rubic 4dr EcoDiesel 4WD'), 
('Wrangler Rubicon 2dr 4WD'), 
('Wrangler Rubicon 4dr 4WD'), 
('Wrangler Unlimited 4WD'), 
('Wrangler/TJ 4WD'), 
('K27'), 
('GS-6'), 
('Revero'), 
('Revero GT'), 
('Kenyon 5.0 Cabrio'), 
('Kenyon 5.0 Coupe'), 
('Kenyon 5.0 Sedan'), 
('Kenyon 5.0 Sp Sedan'), 
('Amanti'), 
('Borrego 2WD'), 
('Borrego 4WD'), 
('Cadenza'), 
('Carnival'), 
('EV6 AWD (Long Range)'), 
('EV6 AWD GT'), 
('EV6 Long Range AWD'), 
('EV6 Long Range RWD'), 
('EV6 RWD (Long Range)'), 
('EV6 RWD (Standard Range)'), 
('EV6 Standard Range RWD'), 
('Forte'), 
('Forte 5'), 
('Forte Eco'), 
('Forte FE'), 
('Forte Koup'), 
('K5'), 
('K5 AWD'), 
('K900'), 
('Niro'), 
('Niro Electric'), 
('Niro FE'), 
('Niro Plug-in Hybrid'), 
('Niro Touring'), 
('Optima'), 
('Optima (2006 New Model)'), 
('Optima FE'), 
('Optima Hybrid'), 
('Optima Hybrid EX'), 
('Optima Plug-in Hybrid'), 
('Optima S'), 
('Rio'), 
('Rio Eco'), 
('Rondo'), 
('Sedona'), 
('Sedona SX'), 
('Sedona SXL'), 
('Seltos AWD'), 
('Seltos FWD'), 
('Sephia'), 
('Sephia/Spectra'), 
('Sorento 2WD'), 
('Sorento 4WD'), 
('Sorento AWD'), 
('Sorento FE AWD'), 
('Sorento FWD'), 
('Sorento Hybrid'), 
('Sorento Hybrid AWD'), 
('Sorento Hybrid FWD'), 
('Sorento Plug-in Hybrid'), 
('Soul'), 
('Soul ECO'), 
('Soul ECO Dynamics'), 
('Soul Electric'), 
('Spectra'), 
('Spectra 1.8L'), 
('Spectra 2.0L'), 
('Sportage 2WD'), 
('Sportage 4WD'), 
('Sportage AWD'), 
('Sportage FE AWD'), 
('Sportage FE FWD'), 
('Sportage FWD'), 
('Sportage Hybrid AWD'), 
('Sportage Hybrid FWD'), 
('Sportage SX AWD'), 
('Sportage SX FWD'), 
('Sportage X-pro'), 
('Stinger AWD'), 
('Stinger RWD'), 
('Telluride AWD'), 
('Telluride FWD'), 
('Agera RS'), 
('Regera'), 
('Laforza'), 
('300E'), 
('Aventador Countach'), 
('Aventador Coupe'), 
('Aventador Coupe LP740-4'), 
('Aventador Roadster'), 
('Aventador Roadster LP740-4'), 
('Aventador S Coupe'), 
('Aventador S Roadster'), 
('Aventador Sian Coupe'), 
('Aventador Sian Roadster'), 
('Aventador Veneno Coupe'), 
('Countach'), 
('Countach Lp500s'), 
('DB132/144 - Diablo'), 
('DB132/144 Diablo'), 
('DB132/Diablo'), 
('Gallardo Coupe'), 
('Gallardo Coupe SL'), 
('Gallardo Spyder'), 
('Huracan'), 
('Huracan 2WD'), 
('Huracan Coupe'), 
('Huracan Coupe 2WD'), 
('Huracan Coupe RWD'), 
('Huracan Spyder'), 
('Huracan Spyder 2WD'), 
('Huracan Spyder RWD'), 
('Huracan Sterrato'), 
('L-140/141 Gallardo'), 
('L-140/715 Gallardo'), 
('L-147 Murcielago'), 
('L-147/148 Murcielago'), 
('Murcielago'), 
('Murcielago Reventon'), 
('Murcielago Reventon Roadster'), 
('Murcielago Roadster'), 
('Urus'), 
('Urus Performante'), 
('Urus S'), 
('Veneno Roadster'), 
('Defender 110'), 
('Defender 110 MHEV'), 
('Defender 130 Outbound'), 
('Defender 130 P300 MHEV'), 
('Defender 130 P400 MHEV'), 
('Defender 90'), 
('Defender 90 MHEV'), 
('Discovery'), 
('Discovery MHEV'), 
('Discovery Series II'), 
('Discovery Sport'), 
('Discovery Sport (286 Hp)'), 
('Discovery Sport MHEV'), 
('Discovery Sport Si4'), 
('Evoque'), 
('Evoque MHEV'), 
('Freelander'), 
('Freelander 3 Door'), 
('Freelander 5 Door'), 
('LR2'), 
('LR3'), 
('LR4'), 
('New Range Rover'), 
('New Range Rover LWB'), 
('New Range Rover P360 LWB MHEV'), 
('New Range Rover P360 MHEV'), 
('New Range Rover P400 LWB MHEV'), 
('New Range Rover P400 MHEV'), 
('New Range Rover Sport'), 
('New Range Rover Sport P360 MHEV'), 
('New Range Rover Sport P400 MHEV'), 
('Range Rover'), 
('Range Rover 4.0'), 
('Range Rover 4.6'), 
('Range Rover County'), 
('Range Rover County Classic'), 
('Range Rover County LWB'), 
('Range Rover Evoque'), 
('Range Rover Evoque (286 Hp)'), 
('Range Rover Evoque 237HP'), 
('Range Rover Evoque 286HP'), 
('Range Rover Evoque Cabriolet'), 
('Range Rover Evoque Convertible'), 
('Range Rover Evoque MHEV'), 
('Range Rover FFV'), 
('Range Rover L FFV'), 
('Range Rover LWB'), 
('Range Rover LWB MHEV'), 
('Range Rover LWB SVA'), 
('Range Rover MHEV'), 
('Range Rover P360 MHEV'), 
('Range Rover P400 MHEV'), 
('Range Rover PHEV'), 
('Range Rover Sport'), 
('Range Rover Sport FFV'), 
('Range Rover Sport MHEV'), 
('Range Rover Sport P360 MHEV'), 
('Range Rover Sport P400 MHEV'), 
('Range Rover Sport PHEV'), 
('Range Rover Sport SVR'), 
('Range Rover Sport SVR MHEV'), 
('Range Rover Sport TDV6'), 
('Range Rover SV Coupe'), 
('Range Rover SV LWB MHEV'), 
('Range Rover SV MHEV'), 
('Range Rover SVA'), 
('Range Rover TDV6'), 
('Range Rover Velar'), 
('Range Rover Velar P300'), 
('Range Rover Velar P340 MHEV'), 
('Range Rover Velar P380'), 
('Range Rover Velar P400 MHEV'), 
('CT 200h'), 
('ES 250'), 
('ES 250 AWD'), 
('ES 300'), 
('ES 300h'), 
('ES 330'), 
('ES 350'), 
('ES 350 F Sport'), 
('GS 200t'), 
('GS 200t F Sport'), 
('GS 300'), 
('GS 300 4WD'), 
('GS 300 F Sport'), 
('GS 300/GS 400'), 
('GS 300/GS 430'), 
('GS 350'), 
('GS 350 AWD'), 
('GS 350 F Sport'), 
('GS 430'), 
('GS 450h'), 
('GS 460'), 
('GS F'), 
('GS300'), 
('GX 460'), 
('GX 470'), 
('HS 250h'), 
('IS 200t'), 
('IS 250'), 
('IS 250 AWD'), 
('IS 250 C'), 
('IS 250/IS 250C'), 
('IS 300'), 
('IS 300 AWD'), 
('IS 350'), 
('IS 350 AWD'), 
('IS 350 C'), 
('IS 350/IS 350C'), 
('IS 500'), 
('IS F'), 
('LC 500'), 
('LC 500 Convertible'), 
('LC 500h'), 
('LFA'), 
('LS 400'), 
('LS 430'), 
('LS 460'), 
('LS 460 AWD'), 
('LS 460 L'), 
('LS 460 L AWD'), 
('LS 500'), 
('LS 500 AWD'), 
('LS 500h'), 
('LS 500h AWD'), 
('LS 600h L'), 
('LX 450'), 
('LX 470'), 
('LX 570'), 
('LX 600'), 
('NX 200t'), 
('NX 200t AWD'), 
('NX 200t AWD F Sport'), 
('NX 250'), 
('NX 250 AWD'), 
('NX 300'), 
('NX 300 AWD'), 
('NX 300 AWD F Sport'), 
('NX 300h'), 
('NX 300h AWD'), 
('NX 350 AWD'), 
('NX 350 AWD F Sport'), 
('NX 350h AWD'), 
('NX 450h Plus AWD'), 
('RC 200t'), 
('RC 300'), 
('RC 300 AWD'), 
('RC 350'), 
('RC 350 AWD'), 
('RC F'), 
('RX 300'), 
('RX 300 4WD'), 
('RX 330 2WD'), 
('RX 330 4WD'), 
('RX 350'), 
('RX 350 2WD'), 
('RX 350 4WD'), 
('RX 350 AWD'), 
('RX 350 L'), 
('RX 350 L AWD'), 
('RX 350h AWD'), 
('RX 400h 2WD'), 
('RX 400h 4WD'), 
('RX 450h'), 
('RX 450h AWD'), 
('RX 450h L AWD'), 
('RX 500h AWD'), 
('RZ 450e AWD'), 
('SC 300/SC 400'), 
('SC 300/SC 430'), 
('SC 430'), 
('UX 200'), 
('UX 250h'), 
('UX 250h AWD'), 
('Aviator 2WD'), 
('Aviator 4WD'), 
('Aviator AWD'), 
('Aviator PHEV AWD'), 
('Aviator RWD'), 
('Blackwood 2WD'), 
('Continental'), 
('Continental  AWD'), 
('Continental  FWD'), 
('Continental Coach'), 
('Corsair AWD'), 
('Corsair AWD PHEV'), 
('Corsair FWD'), 
('LS'), 
('Mark LT'), 
('Mark LT 4WD'), 
('Mark VII'), 
('Mark VIII'), 
('MKC AWD'), 
('MKC FWD'), 
('MKS AWD'), 
('MKS FWD'), 
('MKT AWD'), 
('MKT FWD'), 
('MKT Hearse AWD'), 
('MKT Limo AWD'), 
('MKT Livery AWD'), 
('MKT Livery FWD'), 
('MKX AWD'), 
('MKX FWD'), 
('MKZ AWD'), 
('MKZ FWD'), 
('MKZ Hybrid FWD'), 
('Nautilus AWD'), 
('Nautilus FWD'), 
('Navigator 2WD'), 
('Navigator 2WD FFV'), 
('Navigator 4WD'), 
('Navigator 4WD FFV'), 
('Navigator L 2WD'), 
('Navigator L 4WD'), 
('Navigator Limo. 2WD FFV'), 
('Town Car'), 
('Town Car FFV'), 
('Zephyr'), 
('London Taxi'), 
('Endurance'), 
('98 Esprit V8'), 
('Elan'), 
('Elise/Exige'), 
('Esprit'), 
('Esprit Turbo'), 
('Esprit Turbo HC PI'), 
('Esprit V8'), 
('Evora'), 
('Evora GT'), 
('Air Dream P AWD'), 
('Air Dream R AWD'), 
('Air G Touring AWD'), 
('Air G Touring XR AWD'), 
('Air GT P AWD'), 
('Air Pure AWD'), 
('Air Touring AWD'), 
('TR40'), 
('225'), 
('228'), 
('430'), 
('222E'), 
('BiTurbo'), 
('BiTurbo 425'), 
('BiTurbo Spyder'), 
('Coupe and Gransport'), 
('Coupe Cambiocorsa/Coupe GT'), 
('Coupe Cambiocorsa/GT/G-Sport'), 
('Ghibli'), 
('Ghibli  S RWD'), 
('Ghibli  V6 RWD'), 
('Ghibli GT'), 
('Ghibli Modena AWD'), 
('Ghibli Modena RWD'), 
('Ghibli S'), 
('Ghibli S RWD'), 
('Ghibli SQ4'), 
('Ghibli Trofeo'), 
('Ghibli V6'), 
('Ghibli V6 AWD'), 
('Ghibli V6 SQ4'), 
('Ghibli V6 SQ4 AWD'), 
('GranTurismo'), 
('GranTurismo Convertible'), 
('GranTurismo Modena'), 
('GranTurismo Trofeo'), 
('Grecale GT'), 
('Grecale Modena'), 
('Grecale Trofeo'), 
('Karif'), 
('Levante'), 
('Levante GT'), 
('Levante GTS'), 
('Levante Modena'), 
('Levante Modena V8'), 
('Levante S'), 
('Levante Trofeo'), 
('MC20'), 
('MC20 Spyder'), 
('Q'), 
('Quattroporte'), 
('Quattroporte GT'), 
('Quattroporte GTS'), 
('Quattroporte Modena AWD'), 
('Quattroporte Modena RWD'), 
('Quattroporte S'), 
('Quattroporte SQ4'), 
('Quattroporte SQ4 V6'), 
('Quattroporte Trofeo'), 
('Quattroporte V8'), 
('Quattroporte/QP Sport GT'), 
('Spider Cambiocorsa/Spider GT'), 
('Spyder'), 
('Spyder Cambiocorsa/GT/90 ANV'), 
('57'), 
('62'), 
('57 Zeppelin'), 
('57S'), 
('62S'), 
('Landaulet'), 
('2'), 
('3'), 
('5'), 
('6'), 
('323'), 
('626'), 
('929'), 
('2500 2WD'), 
('3 4-Door'), 
('3 4-Door 2WD'), 
('3 4-Door 4WD'), 
('3 5-Door'), 
('3 5-Door 2WD'), 
('3 5-Door 4WD'), 
('3 DI 4-Door'), 
('3 DI 5-Door'), 
('323 Protege 4x4'), 
('323 Wagon'), 
('323/323 Protege'), 
('6 Sport Wagon'), 
('626/MX-6'), 
('B2000'), 
('B2000/B2200 Pickup 2WD'), 
('B2000/B2200/B2600'), 
('B2200/B2600'), 
('B2200/B2600i'), 
('B2300 2WD'), 
('B2300/B3000/B4000 Pickup 2WD'), 
('B2300/B3000/B4000 Pickup 4WD'), 
('B2500'), 
('B2500 2WD'), 
('B2500/B3000/B4000 2WD'), 
('B2500/B3000/B4000 4WD'), 
('B2600 4x4'), 
('B2600i 4x4'), 
('B3000');
