INSERT INTO VehicleModels (Model)
VALUES
('B3000 (FFV) Ethanol 2WD'), 
('B3000 2WD'), 
('B3000 2WD FFV'), 
('B3000 4WD'), 
('B3000 FFV 2WD'), 
('B3000 FFV 4WD'), 
('B4000'), 
('B4000 2WD'), 
('B4000 4WD'), 
('CX-3 2WD'), 
('CX-3 4WD'), 
('CX-30 2WD'), 
('CX-30 4WD'), 
('CX-5 2WD'), 
('CX-5 4WD'), 
('CX-50 4WD'), 
('CX-7 2WD'), 
('CX-7 4WD'), 
('CX-9 2WD'), 
('CX-9 4WD'), 
('CX-90 4WD'), 
('GLC'), 
('GLC Wagon'), 
('Millenia'), 
('MPV'), 
('MPV 4WD'), 
('MPV 4x4'), 
('MX-3'), 
('MX-30'), 
('MX-5'), 
('MX-5 Miata'), 
('MX-6'), 
('Navajo'), 
('Navajo 4x4'), 
('Protege'), 
('Protege/Protege 5'), 
('Protege/Protege MPS'), 
('RX-7'), 
('RX-8'), 
('Speed 3'), 
('Tribute 2WD'), 
('Tribute 4WD'), 
('Tribute 4WD FFV'), 
('Tribute FWD'), 
('Tribute FWD FFV'), 
('Tribute Hybrid 2WD'), 
('Tribute Hybrid 4WD'), 
('240 DL/240 GL Sedan'), 
('240 DL/240 GL Wagon'), 
('740 GLE Sedan'), 
('740 GLE Wagon'), 
('540C Coupe'), 
('570GT'), 
('570S Coupe'), 
('570S Spider'), 
('600LT Coupe'), 
('600LT Spider'), 
('620R Coupe'), 
('650S Can-Am'), 
('650S Coupe'), 
('650S Spider'), 
('675LT Coupe'), 
('675LT Spider'), 
('720S Coupe'), 
('720S Coupe LM'), 
('720S Spider'), 
('765LT Coupe'), 
('765LT Spider'), 
('Artura'), 
('Elva'), 
('MP4-12C Coupe'), 
('MP4-12C Spider'), 
('MSO HS'), 
('P1'), 
('Sabre'), 
('Senna'), 
('Speedtail'), 
('190'), 
('190 D 2.2/190 E 2.3'), 
('190D 2.5'), 
('190D 2.5 Turbo'), 
('190E'), 
('190E 2.3'), 
('190E 2.3-16'), 
('190E 2.6'), 
('200E'), 
('230CE'), 
('230E'), 
('230TE'), 
('260E'), 
('300CE'), 
('300D'), 
('300D 2.5 Turbo'), 
('300D/300CD'), 
('300E 2.6'), 
('300E 2.8'), 
('300E 4Matic'), 
('300SD'), 
('300SD/380SE'), 
('300SDL'), 
('300SE'), 
('300SEL'), 
('300SL'), 
('300TD'), 
('300TE'), 
('300TE 4Matic'), 
('350SD Turbo'), 
('350SDL Turbo'), 
('380SE'), 
('380SL'), 
('400E'), 
('400SE'), 
('400SEL'), 
('420 SE'), 
('420SE'), 
('420SEL'), 
('500SE'), 
('500SEC'), 
('500SEL'), 
('500SEL 5.0L'), 
('500SEL 5.6L'), 
('500SL'), 
('560SE'), 
('560SEC'), 
('560SEL'), 
('560SL'), 
('600SEL'), 
('600SEL/SEC'), 
('600SL'), 
('A220'), 
('A220 4Matic'), 
('AMG A35 4Matic'), 
('AMG C43 4Matic'), 
('AMG C43 4Matic Convertible'), 
('AMG C43 4Matic Coupe'), 
('AMG C63'), 
('AMG C63 Convertible'), 
('AMG C63 Coupe'), 
('AMG C63 S'), 
('AMG C63 S Convertible'), 
('AMG C63 S Coupe'), 
('AMG CLA35 4Matic'), 
('AMG CLA45 4Matic'), 
('AMG CLS53 4Matic Plus'), 
('AMG CLS63 S 4Matic'), 
('AMG E43 4Matic'), 
('AMG E53 4Matic Plus'), 
('AMG E53 4Matic Plus Convertible'), 
('AMG E53 4Matic Plus Coupe'), 
('AMG E63 4Matic'), 
('AMG E63 S 4Matic'), 
('AMG E63 S 4Matic (Wagon)'), 
('AMG E63 S 4Matic Plus'), 
('AMG E63 S 4Matic Plus (SW)'), 
('AMG E63 S 4Matic Plus (Wagon)'), 
('AMG EQE 4Matic Plus (SUV)'), 
('AMG EQS 4Matic Plus'), 
('AMG G 63 4x4 Squared'), 
('AMG G63'), 
('AMG G65'), 
('AMG GL63'), 
('AMG GLA35 4Matic'), 
('AMG GLA45 4Matic'), 
('AMG GLB35 4Matic'), 
('AMG GLC43 4Matic'), 
('AMG GLC43 4Matic  Coupe'), 
('AMG GLC43 4Matic Coupe'), 
('AMG GLC63 4Matic'), 
('AMG GLC63 4Matic Coupe'), 
('AMG GLC63 4Matic Plus'), 
('AMG GLC63 4Matic Plus Coupe'), 
('AMG GLC63 S 4Matic Coupe'), 
('AMG GLC63 S 4Matic Plus Coupe'), 
('AMG GLE43 4Matic'), 
('AMG GLE43 4Matic Coupe'), 
('AMG GLE53 4Matic Plus'), 
('AMG GLE53 4Matic Plus Coupe'), 
('AMG GLE63'), 
('AMG GLE63 S'), 
('AMG GLE63 S 4Matic Plus'), 
('AMG GLE63 S 4Matic Plus Coupe'), 
('AMG GLE63 S Coupe'), 
('AMG GLS63'), 
('AMG GLS63 4Matic Plus'), 
('AMG GT'), 
('AMG GT 43 4Matic Plus'), 
('AMG GT 53 4Matic Plus'), 
('AMG GT 63 4Matic Plus'), 
('AMG GT 63 S 4Matic Plus'), 
('AMG GT Black Series'), 
('AMG GT C Coupe'), 
('AMG GT C Roadster'), 
('AMG GT Coupe'), 
('AMG GT R Coupe'), 
('AMG GT R Roadster'), 
('AMG GT Roadster'), 
('AMG GT S'), 
('AMG GT S Coupe'), 
('AMG S63 4Matic'), 
('AMG S63 4Matic Convertible'), 
('AMG S63 4Matic Coupe'), 
('AMG S63 4Matic Plus'), 
('AMG S63 4Matic Plus Convertible'), 
('AMG S63 4Matic Plus Coupe'), 
('AMG S65'), 
('AMG S65 Convertible'), 
('AMG S65 Coupe'), 
('AMG SL55 4Matic Plus'), 
('AMG SL63'), 
('AMG SL63 4Matic Plus'), 
('AMG SL65'), 
('AMG SLC43'), 
('AMG SLK55'), 
('B250e'), 
('B-Class Electric Drive'), 
('C220'), 
('C230'), 
('C230 Kompressor'), 
('C230 Kompressor Sports Coupe'), 
('C240'), 
('C240 (Wagon)'), 
('C240 4Matic'), 
('C240 4Matic (Wagon)'), 
('C240 FFV'), 
('C240 FFV (Wagon)'), 
('C250'), 
('C250 Coupe'), 
('C280'), 
('C280 4Matic'), 
('C300'), 
('C300 4Matic'), 
('C300 4Matic Convertible'), 
('C300 4Matic Coupe'), 
('C300 Convertible'), 
('C300 Coupe'), 
('C32 AMG'), 
('C320'), 
('C320 (Wagon)'), 
('C320 4Matic'), 
('C320 4Matic (Wagon)'), 
('C320 4Matic Sedan'), 
('C320 FFV'), 
('C320 FFV (Wagon)'), 
('C320 Sports Coupe'), 
('C320 Sports Coupe FFV'), 
('C350'), 
('C350 4Matic'), 
('C350 4Matic Coupe'), 
('C350 Coupe'), 
('C350e'), 
('C36'), 
('C36 AMG'), 
('C400 4Matic'), 
('C43'), 
('C43 AMG'), 
('C450 AMG'), 
('C55 AMG'), 
('C63 AMG'), 
('C63 AMG Black Series Coupe'), 
('C63 AMG Coupe'), 
('CL500'), 
('CL55 AMG'), 
('CL550'), 
('CL550 4Matic'), 
('CL600'), 
('CL63 AMG'), 
('CL65 AMG'), 
('CLA250'), 
('CLA250 4Matic'), 
('CLA45 AMG 4Matic'), 
('CLK320'), 
('CLK320 (Cabriolet)'), 
('CLK320 Cabriolet'), 
('CLK350'), 
('CLK350 (Cabriolet)'), 
('CLK430'), 
('CLK430 (Cabriolet)'), 
('CLK500'), 
('CLK500 (Cabriolet)'), 
('CLK55 AMG'), 
('CLK55 AMG (Cabriolet)'), 
('CLK550'), 
('CLK550 (Cabriolet)'), 
('CLK63 AMG'), 
('CLK63 AMG (Cabriolet)'), 
('CLS400'), 
('CLS400 4Matic'), 
('CLS450'), 
('CLS450 4Matic'), 
('CLS500'), 
('CLS55 AMG'), 
('CLS550'), 
('CLS550 4Matic'), 
('CLS63 AMG'), 
('CLS63 AMG 4Matic'), 
('CLS63 AMG S'), 
('CLS63 AMG S 4Matic'), 
('E300'), 
('E300 4Matic'), 
('E300 Diesel'), 
('E300 Turbodiesel'), 
('E320'), 
('E320 (Wagon)'), 
('E320 4Matic'), 
('E320 4Matic (Wagon)'), 
('E320 Bluetec'), 
('E320 Cdi'), 
('E320 Convertible'), 
('E320 Coupe'), 
('E320 Sedan'), 
('E320 Sedan 4Matic'), 
('E320 Wagon'), 
('E320 Wagon 4Matic'), 
('E350'), 
('E350 (Wagon)'), 
('E350 4Matic'), 
('E350 4Matic (Wagon)'), 
('E350 4Matic Coupe'), 
('E350 Convertible'), 
('E350 Coupe'), 
('E400'), 
('E400 4Matic'), 
('E400 4Matic (station Wagon)'), 
('E400 4Matic Convertible'), 
('E400 4Matic Coupe'), 
('E400 Convertible'), 
('E400 Coupe'), 
('E400 Hybrid'), 
('E420'), 
('E430'), 
('E430 4Matic'), 
('E450 4Matic'), 
('E450 4Matic (station Wagon)'), 
('E450 4Matic All-Terrain (Wagon)'), 
('E450 4Matic Convertible'), 
('E450 4Matic Coupe'), 
('E450 Convertible'), 
('E450 Coupe'), 
('E500'), 
('E500 (Wagon)'), 
('E500 4Matic'), 
('E500 4Matic (Wagon)'), 
('E55 AMG'), 
('E55 AMG (Wagon)'), 
('E550'), 
('E550 4Matic'), 
('E550 Convertible'), 
('E550 Coupe'), 
('E63 AMG'), 
('E63 AMG (Wagon)'), 
('E63 AMG 4Matic'), 
('E63 AMG 4Matic (Wagon)'), 
('E63 AMG S'), 
('E63 AMG S 4Matic'), 
('E63 AMG S 4Matic (Wagon)'), 
('EQB 300 4Matic'), 
('EQB 350 4Matic'), 
('EQS 450 4Matic'), 
('EQS 450 4Matic (SUV)'), 
('EQS 450 Plus'), 
('EQS 450 Plus (SUV)'), 
('EQS 580 4Matic'), 
('EQS 580 4Matic (SUV)'), 
('G500'), 
('G55 AMG'), 
('G550'), 
('G550 4x4'), 
('G550 4x4 (Special Off-Road Model)'), 
('G63 AMG'), 
('GL320 CDI 4Matic'), 
('GL450 4Matic'), 
('GL550 4Matic'), 
('GL63 AMG'), 
('GLA250'), 
('GLA250 4Matic'), 
('GLA45 AMG 4Matic'), 
('GLB250'), 
('GLB250 4Matic'), 
('GLC300'), 
('GLC300 4Matic'), 
('GLC300 4Matic Coupe'), 
('GLC350e 4Matic'), 
('GLE300 d 4Matic'), 
('GLE350'), 
('GLE350 4Matic'), 
('GLE350 d 4Matic'), 
('GLE400 4Matic'), 
('GLE450 4Matic'), 
('GLE450 AMG Coupe'), 
('GLE550e 4Matic'), 
('GLE580 4Matic'), 
('GLK250 Bluetec 4Matic'), 
('GLK350'), 
('GLK350 4Matic'), 
('GLS450 4Matic'), 
('GLS550 4Matic'), 
('GLS580 4Matic'), 
('GLS600 4Matic Maybach'), 
('Maybach S 600'), 
('Maybach S550 4Matic'), 
('Maybach S560 4Matic'), 
('Maybach S600'), 
('Maybach S650'), 
('Maybach S650 Convertible'), 
('Maybach S680 4Matic'), 
('Metris (Cargo Van)'), 
('Metris (Cargo Van, LWB)'), 
('Metris (Passenger Van)'), 
('Metris (US Postal Long)'), 
('Metris (US Postal)'), 
('ML250 Bluetec 4Matic'), 
('ML320'), 
('ML320 CDI 4Matic'), 
('ML350'), 
('ML350 4Matic'), 
('ML400 4Matic'), 
('ML430'), 
('ML450 Hybrid 4Matic'), 
('ML500'), 
('ML500 4Matic'), 
('ML55'), 
('ML55 AMG'), 
('ML550 4Matic'), 
('ML63 AMG'), 
('R320 CDI 4Matic'), 
('R350'), 
('R350 4Matic'), 
('R500'), 
('R500 4Matic'), 
('R63 AMG'), 
('S320'), 
('S350'), 
('S350D'), 
('S400 Hybrid'), 
('S420'), 
('S430'), 
('S430 4Matic'), 
('S450'), 
('S450 4Matic'), 
('S500'), 
('S500 4Matic'), 
('S500 Coupe'), 
('S500 Sedan'), 
('S55 AMG'), 
('S550'), 
('S550 4Matic'), 
('S550 4Matic Coupe'), 
('S550 Convertible'), 
('S550e'), 
('S560'), 
('S560 4Matic'), 
('S560 4Matic Coupe'), 
('S560 4Matic Maybach'), 
('S560 Convertible'), 
('S560e'), 
('S580 4Matic'), 
('S580 4Matic Maybach'), 
('S600'), 
('S600 Coupe'), 
('S600 Sedan'), 
('S63 AMG'), 
('S63 AMG 4Matic'), 
('S63 AMG 4Matic Coupe'), 
('S65 AMG'), 
('S65 AMG Convertible'), 
('S65 AMG Coupe'), 
('SL320'), 
('SL400'), 
('SL450'), 
('SL500'), 
('SL55 AMG'), 
('SL550'), 
('SL600'), 
('SL63 AMG'), 
('SL65 AMG'), 
('SLC300'), 
('SLK230'), 
('SLK230 Kompressor'), 
('SLK250'), 
('SLK280'), 
('SLK300'), 
('SLK32 AMG'), 
('SLK320'), 
('SLK350'), 
('SLK55 AMG'), 
('SLR'), 
('SLS AMG'), 
('SLS AMG Black Series Coupe'), 
('SLS AMG Coupe'), 
('SLS AMG GT Coupe'), 
('SLS AMG GT Roadster'), 
('SLS AMG Roadster'), 
('Capri'), 
('Cougar'), 
('Grand Marquis'), 
('Grand Marquis FFV'), 
('Grand Marquis Wagon'), 
('Lynx'), 
('Lynx Wagon'), 
('Marauder'), 
('Mariner 2WD'), 
('Mariner 4WD'), 
('Mariner 4WD FFV'), 
('Mariner FWD'), 
('Mariner FWD FFV'), 
('Mariner Hybrid 4WD'), 
('Mariner Hybrid FWD'), 
('Marquis'), 
('Marquis Wagon'), 
('Milan'), 
('Milan AWD'), 
('Milan AWD FFV'), 
('Milan FFV'), 
('Milan FWD'), 
('Milan FWD FFV'), 
('Milan Hybrid FWD'), 
('Milan S'), 
('Milan S FWD'), 
('Montego AWD'), 
('Montego FWD'), 
('Monterey Wagon FWD'), 
('Mountaineer 2WD'), 
('Mountaineer 2WD FFV'), 
('Mountaineer 4WD'), 
('Mountaineer 4WD FFV'), 
('Mountaineer AWD'), 
('Mountaineer FFV 2WD'), 
('Mountaineer FFV 4WD'), 
('Mystique'), 
('Sable'), 
('Sable (FFV)'), 
('Sable AWD'), 
('Sable FWD'), 
('Sable Wagon'), 
('Sable Wagon (FFV)'), 
('Sable Wagon 3.0 A/C'), 
('Sable Wagon V6 A/C'), 
('Topaz'), 
('Topaz AWD'), 
('Tracer'), 
('Tracer Wagon'), 
('Villager FWD Van'), 
('Villager FWD Wagon'), 
('Scorpio'), 
('XR4Ti'), 
('Clubman'), 
('Clubman S'), 
('Cooper'), 
('Cooper (3-doors)'), 
('Cooper (5-doors)'), 
('Cooper Clubman'), 
('Cooper Clubman All4'), 
('Cooper Clubvan'), 
('Cooper Convertible'), 
('Cooper Countryman'), 
('Cooper Countryman All4'), 
('Cooper Countryman Coupe'), 
('Cooper Coupe'), 
('Cooper Hardtop 2 door'), 
('Cooper Hardtop 4 door'), 
('Cooper Paceman'), 
('Cooper Roadster'), 
('Cooper S'), 
('Cooper S (3-doors)'), 
('Cooper S (5-doors)'), 
('Cooper S Clubman'), 
('Cooper S Clubman All4'), 
('Cooper S Convertible'), 
('Cooper S Countryman'), 
('Cooper S Countryman All4'), 
('Cooper S Countryman Coupe'), 
('Cooper S Countryman Coupe All4'), 
('Cooper S Coupe'), 
('Cooper S Hardtop 2 door'), 
('Cooper S Hardtop 4 door'), 
('Cooper S JCWorks GP Kit'), 
('Cooper S Paceman'), 
('Cooper S Paceman All4'), 
('Cooper S Roadster'), 
('Cooper SE Countryman All4'), 
('Cooper SE Hardtop 2 door'), 
('JCW Countryman All4'), 
('JCW Countryman Coupe All4'), 
('JCW Paceman All4'), 
('John Cooper Works'), 
('John Cooper Works Clubman'), 
('John Cooper Works Clubman All4'), 
('John Cooper Works Convertible'), 
('John Cooper Works Coupe'), 
('John Cooper Works GP'), 
('John Cooper Works GP-2'), 
('John Cooper Works Hardtop'), 
('John Cooper Works Hardtop 2 door'), 
('John Cooper Works Roadster'), 
('MiniE'), 
('3000 GT'), 
('3000 GT Spyder'), 
('Cordia'), 
('Diamante'), 
('Diamante Sedan'), 
('Diamante Wagon'), 
('Eclipse'), 
('Eclipse Convertible'), 
('Eclipse Cross 2WD'), 
('Eclipse Cross 4WD'), 
('Eclipse Cross ES 2WD'), 
('Eclipse Cross ES 4WD'), 
('Eclipse Spyder'), 
('Endeavor'), 
('Endeavor 2WD'), 
('Endeavor 4WD'), 
('Endeavor AWD'), 
('Expo'), 
('Expo.LRV'), 
('Galant'), 
('Galant Sigma'), 
('i-MiEV'), 
('Lancer 4WD'), 
('Lancer AWD'), 
('Lancer Evolution'), 
('Lancer Sportback'), 
('Mirage'), 
('Mirage G4'), 
('Mirage Wagon'), 
('Montero'), 
('Montero 4WD'), 
('Montero Sport 2WD'), 
('Montero Sport 4WD'), 
('Nativa 2WD'), 
('Nativa 2WD (Puerto Rico Only)'), 
('Nativa 2WD(Puerto Rico Only)'), 
('Nativa 4WD'), 
('Nativa 4WD (Puerto Rico Only)'), 
('Outlander 2WD'), 
('Outlander 4WD'), 
('Outlander PHEV'), 
('Outlander Sport 2WD'), 
('Outlander Sport 4WD'), 
('Raider Pickup 2WD'), 
('Raider Pickup 4WD'), 
('Sigma'), 
('Space Wagon'), 
('Space Wagon 4WD'), 
('Starion'), 
('Tredia'), 
('Truck 2WD'), 
('Truck 4WD'), 
('Van'), 
('Wagon'), 
('MV-1'), 
('MV-1 CNG'), 
('Plus Eight'), 
('200SX'), 
('240SX'), 
('300ZX'), 
('300ZX 2x2'), 
('350z'), 
('350z Roadster'), 
('370z'), 
('370z Roadster'), 
('Altima'), 
('Altima / Stanza'), 
('Altima AWD'), 
('Altima AWD SR/Platinum'), 
('Altima Coupe'), 
('Altima Hybrid'), 
('Altima SL/SR'), 
('Altima SR'), 
('Altima SR/Platinum'), 
('Altima SV/SL'), 
('Altra EV'), 
('ARIYA ENG Plus/EVO Plus e-4ORCE 87kWh'), 
('ARIYA ENGAGE e-4ORCE 63kWh'), 
('ARIYA ENGAGE FWD 63kWh'), 
('ARIYA EVO Plus/EMP Plus/PRM FWD 87kWh'), 
('ARIYA PLAT Plus e-4ORCE 87kWh 19'), 
('ARIYA PLAT Plus e-4ORCE 87kWh 20'), 
('ARIYA VENTURE Plus FWD 87kWh'), 
('Armada 2WD'), 
('Armada 2WD FFV'), 
('Armada 4WD'), 
('Armada 4WD FFV'), 
('Axxess'), 
('Axxess AWD'), 
('Cube'), 
('Frontier 2WD'), 
('Frontier 2WD FFV'), 
('Frontier 4WD'), 
('Frontier 4WD FFV'), 
('Frontier 4WD PRO4X'), 
('Frontier V6 2WD'), 
('Frontier V6 4WD'), 
('GT-R'), 
('Hardbody 2WD'), 
('Hardbody 4WD'), 
('Hyper-Mini'), 
('Juke'), 
('Juke AWD'), 
('Juke Nismo RS'), 
('Juke Nismo RS AWD'), 
('Kicks'), 
('Leaf'), 
('Leaf (24 kW-hr battery pack)'), 
('Leaf (30 kW-hr battery pack)'), 
('Leaf (40 kW-hr battery pack)'), 
('Leaf (62 kW-hr battery pack)'), 
('Leaf SV'), 
('Leaf SV/SL (62 kW-hr battery pack)'), 
('Maxima'), 
('Maxima Wagon'), 
('Murano 2WD'), 
('Murano AWD'), 
('Murano CrossCabriolet'), 
('Murano FWD'), 
('Murano Hybrid AWD'), 
('Murano Hybrid FWD'), 
('NV200 Cargo Van'), 
('NV200 NYC Taxi'), 
('NX'), 
('NX Coupe'), 
('Pathfinder 2WD'), 
('Pathfinder 4WD'), 
('Pathfinder 4WD Platinum'), 
('Pathfinder 4WD Rock Creek'), 
('Pathfinder 4WD SL/Platinum'), 
('Pathfinder Armada 2WD'), 
('Pathfinder Armada 4WD'), 
('Pathfinder FE 2WD'), 
('Pathfinder Hybrid 2WD'), 
('Pathfinder Hybrid 4WD'), 
('Pathfinder Van (cargo)'), 
('Pickup Cab Chassis'), 
('Pulsar NX'), 
('Pulsar/Pulsar-NX'), 
('Quest'), 
('Rogue AWD'), 
('Rogue AWD  SV/SL/Platinum'), 
('Rogue AWD SL/Platinum'), 
('Rogue FWD'), 
('Rogue FWD  SV/SL/Platinum'), 
('Rogue FWD SL/Platinum'), 
('Rogue Hybrid  AWD'), 
('Rogue Hybrid  FWD'), 
('Rogue Select AWD'), 
('Rogue Select FWD'), 
('Rogue Sport'), 
('Rogue Sport AWD'), 
('Rogue Sport FWD'), 
('Sentra'), 
('Sentra Classic'), 
('Sentra Coupe'), 
('Sentra FE'), 
('Sentra Honeybee'), 
('Sentra Nismo'), 
('Sentra SR'), 
('Sentra Wagon'), 
('Sentra Wagon 4WD'), 
('Sentra/200SX'), 
('Stanza'), 
('Stanza Wagon 2WD'), 
('Stanza Wagon 4WD'), 
('Titan 2WD'), 
('Titan 2WD FFV'), 
('Titan 4WD'), 
('Titan 4WD  PRO4X'), 
('Titan 4WD FFV'), 
('Titan 4WD PRO4X'), 
('Titan 4WD PRO-4X'), 
('Titan FE 2WD'), 
('Titan FE 2WD FFV'), 
('Truck 2WD (new Version)'), 
('Truck 4WD (new Version)'), 
('Truck Cab Chassis 2WD'), 
('Van (cargo)'), 
('Van (passenger)'), 
('Van(cargo)'), 
('Versa'), 
('Versa FE'), 
('Xterra 2WD'), 
('Xterra 4WD'), 
('Xterra V6 2WD'), 
('Xterra V6 4WD'), 
('Z'), 
('Z NISMO'), 
('Achieva'), 
('Alero'), 
('Bravada 2WD'), 
('Bravada AWD'), 
('Calais'), 
('Ciera SL'), 
('Ciera SL Wagon'), 
('Custom Cruiser'), 
('Custom Cruiser Wagon'), 
('Cutlass'), 
('Cutlass Calais'), 
('Cutlass Ciera'), 
('Cutlass Cruiser'), 
('Cutlass Cruiser Wagon'), 
('Cutlass Supreme'), 
('Cutlass Supreme Classic'), 
('Delta 88'), 
('Delta 88 Royale'), 
('Eighty-Eight'), 
('Eighty-Eight/Regency'), 
('Eighty-Eight/Regency/LSS'), 
('Firenza'), 
('Firenza Cruiser'), 
('Firenza Cruiser Wagon'), 
('Intrigue'), 
('Ninety-Eight'), 
('Ninety-Eight II'), 
('Ninety-Eight Regency'), 
('Ninety-Eight/Touring'), 
('Omega'), 
('Silhouette 2WD'), 
('Silhouette AWD'), 
('Toronado'), 
('Trofeo/Toronado'), 
('Huayra'), 
('Huayra Coupe'), 
('Huayra Roadster BC'), 
('Roadster'), 
('Panoz Roadster'), 
('Kallista'), 
('Pas-Syclone'), 
('Pas-Typhoon'), 
('505'), 
('405 Sedan'), 
('405 Sports Wagon'), 
('405 Station Wagon'), 
('505 Sedan'), 
('505 Station Wagon'), 
('505 Wagon'), 
('604 Sedan'), 
('Acclaim'), 
('Breeze'), 
('Caravelle'), 
('Gran Fury'), 
('Horizon'), 
('Reliant'), 
('Reliant Wagon'), 
('Sundance'), 
('Sundance Convertible'), 
('Sundance/Duster'), 
('Turismo'), 
('Voyager 2WD'), 
('Voyager/Grand Voyager 2WD'), 
('Voyager/Grand Voyager 4WD'), 
('1'), 
('2 BST edition'), 
('2 Dual Motor'), 
('2 Dual Motor Perf Pack'), 
('2 Dual Motor Performance Pack'), 
('2 Single Motor'), 
('1000'), 
('6000'), 
('2000 Sunbird'), 
('2000 Sunbird Convertible'), 
('2000 Sunbird Wagon'), 
('20th Anniversary Trans Am'), 
('6000 Wagon'), 
('Aztek AWD'), 
('Aztek FWD'), 
('Bonneville'), 
('Fiero'), 
('Firebird'), 
('Firebird/Formula'), 
('Firebird/Trans Am'), 
('Firebird/Trans Am/Formula'), 
('Firefly'), 
('Firefly FE'), 
('G3 (3-Door)'), 
('G3 (5-Door)'), 
('G3 Wave'), 
('G3 Wave 5'), 
('G5'), 
('G5 GT'), 
('G5 XFE'), 
('G5/Pursuit'), 
('G6'), 
('G6 GT/GTP Convertible'), 
('G8'), 
('Grand Am'), 
('Grand Prix'), 
('Grand Prix Ste Turbo'), 
('Grand Prix Turbo'), 
('GTO'), 
('Lemans'), 
('Montana AWD'), 
('Montana FWD'), 
('Montana SV6 AWD'), 
('Montana SV6 FWD'), 
('Montana SVX AWD'), 
('Montana SVX FWD'), 
('Parisienne'), 
('Parisienne Wagon'), 
('Phoenix'), 
('Safari Wagon'), 
('Solstice'), 
('Sunbird'), 
('Sunbird Convertible'), 
('Sunbird Wagon'), 
('Sunburst'), 
('Sunfire'), 
('Torrent AWD'), 
('Torrent FWD'), 
('Trans Sport 2WD'), 
('Trans Sport/Montana 2WD'), 
('Turbo Firefly'), 
('Vibe'), 
('Vibe AWD'), 
('Wave'), 
('Wave 5'), 
('911'), 
('944'), 
('968'), 
('718 Boxster'), 
('718 Boxster GTS'), 
('718 Boxster S'), 
('718 Boxster T'), 
('718 Cayman'), 
('718 Cayman GT4'), 
('718 Cayman GTS'), 
('718 Cayman S'), 
('718 Cayman T'), 
('718 GT4 RS'), 
('718 Spyder'), 
('911 C4 GTS'), 
('911 C4 GTS Cabriolet'), 
('911 Carrera'), 
('911 Carrera 2/4'), 
('911 Carrera 4'), 
('911 Carrera 4 Cabriolet'), 
('911 Carrera 4 GTS'), 
('911 Carrera 4 GTS Cabriolet'), 
('911 Carrera 4 Targa'), 
('911 Carrera 4/2'), 
('911 Carrera 4S'), 
('911 Carrera 4S Cabriolet'), 
('911 Carrera 4S Targa'), 
('911 Carrera Cabriolet'), 
('911 Carrera GTS'), 
('911 Carrera GTS Cabriolet'), 
('911 Carrera S'), 
('911 Carrera S Cabriolet'), 
('911 Carrera T'), 
('911 GT2');
