INSERT INTO VehicleModels (Model)
VALUES
('2.2CL/3.0CL'), 
('2.3CL/3.0CL'), 
('2.5TL'), 
('2.5TL/3.2TL'), 
('3.2CL'), 
('3.2TL'), 
('3.5RL'), 
('ILX'), 
('ILX Hybrid'), 
('Integra'), 
('Integra A-Spec'), 
('Legend'), 
('MDX'), 
('MDX 2WD'), 
('MDX 4WD'), 
('MDX AWD'), 
('MDX AWD A-SPEC'), 
('MDX AWD Type-S'), 
('MDX FWD'), 
('MDX Hybrid AWD'), 
('NSX'), 
('NSX Hybrid'), 
('RDX 2WD'), 
('RDX 4WD'), 
('RDX AWD'), 
('RDX AWD A-SPEC'), 
('RDX FWD'), 
('RDX FWD A-SPEC'), 
('RL'), 
('RLX'), 
('RLX Hybrid'), 
('RSX'), 
('SLX'), 
('TL'), 
('TL 2WD'), 
('TL 4WD'), 
('TLX'), 
('TLX 2WD'), 
('TLX 4WD'), 
('TLX AWD'), 
('TLX AWD A-SPEC'), 
('TLX FWD'), 
('TLX FWD A-SPEC'), 
('TLX Type-S'), 
('TLX Type-S Perf Tire'), 
('TSX'), 
('TSX Wagon'), 
('Vigor'), 
('ZDX 4WD'), 
('164'), 
('4C'), 
('8 C Spider'), 
('Giulia'), 
('Giulia AWD'), 
('GT V6 2.5'), 
('GTV'), 
('Milano'), 
('Spider'), 
('Spider Veloce 2000'), 
('Stelvio'), 
('Stelvio AWD'), 
('DJ Po Vehicle 2WD'), 
('FJ8c Post Office'), 
('Post Office DJ5 2WD'), 
('Post Office DJ8 2WD'), 
('Eagle'), 
('Eagle 4DR Wagon'), 
('Eagle 4WD'), 
('Eagle SX/4 4WD'), 
('GNX'), 
('DB AR1'), 
('DB11 V12'), 
('DB11 V8'), 
('DB7 Coupe'), 
('DB-7 GT Coupe'), 
('DB-7 GT Volante'), 
('DB-7 Vantage Coupe'), 
('DB-7 Vantage Volante'), 
('DB7 Volante'), 
('DB9'), 
('DB9 Coupe'), 
('DB9 Coupe Manual'), 
('DB9 Volante'), 
('DB9 Volante Manual'), 
('DBS'), 
('DBS Coupe'), 
('DBX 707'), 
('DBX V8'), 
('Lagonda'), 
('Rapide'), 
('Rapide S'), 
('Saloon/Vantage/Volante'), 
('V12 Vanquish'), 
('V12 Vanquish S'), 
('V12 Vantage'), 
('V12 Vantage S'), 
('V8 Vantage'), 
('V8 Vantage ASM'), 
('V8 Vantage S'), 
('Vanquish'), 
('Vanquish S'), 
('Vanquish S Zagato'), 
('Vantage GT'), 
('Vantage Manual'), 
('Vantage V12'), 
('Vantage V8'), 
('Virage'), 
('Virage Saloon'), 
('Virage/Volante'), 
('80'), 
('90'), 
('100'), 
('200'), 
('4000'), 
('100 quattro'), 
('100 quattro Wagon'), 
('100 Wagon'), 
('200 quattro'), 
('200 quattro 20v'), 
('200 quattro 20v Wagon'), 
('200 quattro Wagon'), 
('4000 CS quattro'), 
('4000 S'), 
('4000 S quattro'), 
('4000s'), 
('4000s quattro'), 
('5000 CS quattro'), 
('5000 CS quattro Wagon'), 
('5000 CS Turbo'), 
('5000 S'), 
('5000 S quattro'), 
('5000S'), 
('5000S Wagon'), 
('80 quattro'), 
('80/90'), 
('80/90 quattro'), 
('90 quattro'), 
('90 quattro 20v'), 
('A3'), 
('A3 Cabriolet'), 
('A3 Cabriolet quattro'), 
('A3 e-tron'), 
('A3 e-tron ultra'), 
('A3 quattro'), 
('A4'), 
('A4 Allroad quattro'), 
('A4 Avant'), 
('A4 Avant quattro'), 
('A4 Cabriolet'), 
('A4 Cabriolet quattro'), 
('A4 quattro'), 
('A4 S line quattro'), 
('A4 S-Line quattro'), 
('A4 Ultra'), 
('A5 Cabriolet'), 
('A5 Cabriolet quattro'), 
('A5 Coupe quattro'), 
('A5 quattro'), 
('A5 Sportback quattro'), 
('A5 Sportback S line quattro'), 
('A5 Sportback S-Line quattro'), 
('A6'), 
('A6 Allroad'), 
('A6 Allroad quattro'), 
('A6 Avant quattro'), 
('A6 quattro'), 
('A6 quattro Wagon'), 
('A6 Wagon'), 
('A6 Wagon quattro'), 
('A7'), 
('A7 quattro'), 
('A7 TFSI e quattro'), 
('A8'), 
('A8 L'), 
('A8 L quattro'), 
('A8 quattro'), 
('Allroad'), 
('Allroad quattro'), 
('Cabriolet'), 
('Coupe GT'), 
('Coupe quattro'), 
('e-tron'), 
('e-tron GT'), 
('e-tron quattro'), 
('e-tron S'), 
('e-tron S Sportback'), 
('e-tron Sportback'), 
('e-tron Sportback quattro'), 
('Q3'), 
('Q3 quattro'), 
('Q3 S line quattro'), 
('Q3 S-Line'), 
('Q3 S-line quattro'), 
('Q4 40 e-tron'), 
('Q4 50 e-tron quattro'), 
('Q4 e-tron'), 
('Q4 e-tron quattro'), 
('Q4 e-tron Sportback'), 
('Q4 e-tron Sportback quattro'), 
('Q4 Sportback 50 e-tron quattro'), 
('Q5'), 
('Q5 Hybrid'), 
('Q5 quattro'), 
('Q5 S line quattro'), 
('Q5 S-Line quattro'), 
('Q5 Sportback'), 
('Q5 Sportback S line quattro'), 
('Q5 Sportback S-line quattro'), 
('Q5 TFSI e quattro'), 
('Q7'), 
('Q7 quattro'), 
('Q8'), 
('Q8 e-tron quattro'), 
('Q8 quattro'), 
('Q8 Sportback e-tron ultra quattro'), 
('Quattro'), 
('R8'), 
('R8 2WD'), 
('R8 AWD'), 
('R8 Coupe'), 
('R8 Coupe quattro'), 
('R8 Coupe RWD'), 
('R8 GT RWD'), 
('R8 RWD'), 
('R8 Spyder'), 
('R8 Spyder 2WD'), 
('R8 Spyder AWD'), 
('R8 Spyder quattro'), 
('R8 Spyder RWD'), 
('RS 3'), 
('RS 5'), 
('RS 5 Cabriolet'), 
('RS 5 Coupe'), 
('RS 5 Sportback'), 
('RS 6 Avant'), 
('RS 7'), 
('RS e-tron GT'), 
('RS Q8'), 
('RS3'), 
('RS4'), 
('RS4 Cabriolet'), 
('RS6'), 
('S3'), 
('S4'), 
('S4 Avant'), 
('S4 Cabriolet'), 
('S5'), 
('S5 Cabriolet'), 
('S5 Coupe'), 
('S5 Sportback'), 
('S6'), 
('S6 Avant'), 
('S6 Wagon'), 
('S7'), 
('S8'), 
('S8 quattro'), 
('SQ5'), 
('SQ5 Sportback'), 
('SQ7'), 
('SQ8'), 
('TT Coupe'), 
('TT Coupe quattro'), 
('TT Roadster'), 
('TT Roadster quattro'), 
('TT RS'), 
('TT RS Coupe'), 
('TTS Coupe'), 
('TTS Coupe quattro'), 
('V8'), 
('Aurora'), 
('A.C.MARK IV'), 
('A.C.Mkiv'), 
('Avanti II'), 
('Transit Connect Electric Van/Wagon'), 
('Arnage'), 
('Arnage LWB'), 
('Arnage RL'), 
('Azure'), 
('Bentayga'), 
('Bentayga EWB'), 
('Bentayga Speed'), 
('Brooklands'), 
('Brooklands R'), 
('Brooklands R Limo'), 
('Continental Flying Spur'), 
('Continental GT'), 
('Continental GT Convertible'), 
('Continental GT Convertible Speed'), 
('Continental GT Speed'), 
('Continental GT Speed Convertible'), 
('Continental GT V8 Convertible'), 
('Continental GT3-R'), 
('Continental GTC'), 
('Continental R'), 
('Continental SC'), 
('Continental Supersports'), 
('Continental Supersports Convertible'), 
('Continental T'), 
('Flying Spur'), 
('Flying Spur Hybrid'), 
('Mulsanne'), 
('Mulsanne EWB'), 
('Turbo RT'), 
('X1/9'), 
('Dovell 230CE'), 
('Dovell 230E'), 
('Bitter SC'), 
('SC'), 
('128ci Convertible'), 
('128i'), 
('128i Convertible'), 
('135i'), 
('135i Convertible'), 
('228i'), 
('228i Convertible'), 
('228i Gran Coupe'), 
('228i xDrive'), 
('228i xDrive Convertible'), 
('228i xDrive Gran Coupe'), 
('230i Convertible'), 
('230i Coupe'), 
('230i xDrive Convertible'), 
('230i xDrive Coupe'), 
('3 Series'), 
('318i'), 
('318i Convertible'), 
('318i/318is'), 
('318is'), 
('318is Convertible'), 
('318ti'), 
('320i'), 
('320i xDrive'), 
('323ci'), 
('323i'), 
('323i Convertible'), 
('323i Touring'), 
('323is'), 
('325ci'), 
('325ci Convertible'), 
('325i'), 
('325i Convertible'), 
('325i Sport Wagon'), 
('325i/325is'), 
('325ic'), 
('325is'), 
('325ix'), 
('325xi'), 
('325xi Sport Wagon'), 
('328ci'), 
('328ci Convertible'), 
('328ci xDrive'), 
('328cxi'), 
('328d'), 
('328d xDrive'), 
('328d xDrive Sports Wagon'), 
('328i'), 
('328i Convertible'), 
('328i Coupe'), 
('328i Coupe xDrive'), 
('328i Sport Wagon'), 
('328i Sport Wagon xDrive'), 
('328i Sports Wagon'), 
('328i xDrive'), 
('328i xDrive Gran Turismo'), 
('328i xDrive Sport Wagon'), 
('328i xDrive Sports Wagon'), 
('328i/328is'), 
('328ic'), 
('328is'), 
('328xi'), 
('328xi Sport Wagon'), 
('330ci'), 
('330ci Convertible'), 
('330e'), 
('330e Sedan'), 
('330e xDrive'), 
('330e xDrive Sedan'), 
('330i'), 
('330i Sedan'), 
('330i xDrive'), 
('330i xDrive Gran Turismo'), 
('330i xDrive Sedan'), 
('330i xDrive Sports Wagon'), 
('330xi'), 
('335ci'), 
('335ci Convertible'), 
('335ci xDrive'), 
('335cxi'), 
('335d'), 
('335i'), 
('335i Convertible'), 
('335i Coupe'), 
('335i Coupe xDrive'), 
('335i xDrive'), 
('335i xDrive Gran Turismo'), 
('335is Convertible'), 
('335is Coupe'), 
('335xi'), 
('340i'), 
('340i xDrive'), 
('340i xDrive Gran Turismo'), 
('428i Convertible'), 
('428i Coupe'), 
('428i Gran Coupe'), 
('428i xDrive Convertible'), 
('428i xDrive Coupe'), 
('428i xDrive Gran Coupe'), 
('430i Convertible'), 
('430i Coupe'), 
('430i Gran Coupe'), 
('430i xDrive Convertible'), 
('430i xDrive Coupe'), 
('430i xDrive Gran Coupe'), 
('435i Convertible'), 
('435i Coupe'), 
('435i Gran Coupe'), 
('435i xDrive Convertible'), 
('435i xDrive Coupe'), 
('435i xDrive Gran Coupe'), 
('440i Convertible'), 
('440i Coupe'), 
('440i Gran Coupe'), 
('440i xDrive Convertible'), 
('440i xDrive Coupe'), 
('440i xDrive Gran Coupe'), 
('5 Series'), 
('525i'), 
('525i Sport Wagon'), 
('525i Touring'), 
('525xi'), 
('528i'), 
('528i Sport Wagon'), 
('528i Touring'), 
('528i xDrive'), 
('528xi'), 
('530e'), 
('530e Sedan'), 
('530e xDrive'), 
('530e xDrive Sedan'), 
('530i'), 
('530i Sedan'), 
('530i Touring'), 
('530i xDrive'), 
('530i xDrive Sedan'), 
('530xi'), 
('530xi Sport Wagon'), 
('535d'), 
('535d xDrive'), 
('535i'), 
('535i Gran Turismo'), 
('535i Sport Wagon xDrive'), 
('535i xDrive'), 
('535i xDrive Gran Turismo'), 
('535xi'), 
('535xi Sport Wagon'), 
('540d xDrive'), 
('540i'), 
('540i Sedan'), 
('540i Sport Wagon'), 
('540i Touring'), 
('540i xDrive'), 
('540i xDrive Sedan'), 
('545i'), 
('550 GT'), 
('550i'), 
('550i Gran Turismo'), 
('550i xDrive'), 
('550i xDrive Gran Turismo'), 
('550i xDrive GT'), 
('6 Series'), 
('635csi'), 
('640i Convertible'), 
('640i Coupe'), 
('640i Gran Coupe'), 
('640i xDrive Convertible'), 
('640i xDrive Coupe'), 
('640i xDrive Gran Coupe'), 
('640i xDrive Gran Turismo'), 
('645ci'), 
('645ci Convertible'), 
('650ci'), 
('650ci Convertible'), 
('650i Convertible'), 
('650i Convertible xDrive'), 
('650i Coupe'), 
('650i Coupe xDrive'), 
('650i Gran Coupe'), 
('650i xDrive Convertible'), 
('650i xDrive Coupe'), 
('650i xDrive Gran Coupe'), 
('7 Series'), 
('735i'), 
('735i Luxury'), 
('735il'), 
('740e xDrive'), 
('740i'), 
('740i Sedan'), 
('740i xDrive'), 
('740i xDrive Sedan'), 
('740i/740i Sport'), 
('740il'), 
('740il/740il Protection'), 
('740Ld xDrive'), 
('740Li'), 
('740Li xDrive'), 
('745e xDrive'), 
('745i'), 
('745li'), 
('750 Series'), 
('750i'), 
('750i xDrive'), 
('750i xDrive Sedan'), 
('750il'), 
('750il/750il Protection'), 
('750Li'), 
('750Li xDrive'), 
('760i'), 
('760i xDrive Sedan'), 
('760Li'), 
('840ci'), 
('840i Convertible'), 
('840i Coupe'), 
('840i Gran Coupe'), 
('840i xDrive Convertible'), 
('840i xDrive Coupe'), 
('840i xDrive Gran Coupe'), 
('850ci'), 
('850csi'), 
('850i'), 
('Active E'), 
('ActiveHybrid 3'), 
('ActiveHybrid 5'), 
('ActiveHybrid 7'), 
('ActiveHybrid 7i'), 
('ActiveHybrid 7L'), 
('ActiveHybrid 7Li'), 
('ActiveHybrid X6'), 
('Alpina B6 Gran Coupe xDrive'), 
('Alpina B6 xDrive Gran Coupe'), 
('Alpina B7'), 
('Alpina B7 LWB'), 
('Alpina B7 LWB xDrive'), 
('Alpina B7 SWB'), 
('Alpina B7 SWB xDrive'), 
('Alpina B7 xDrive'), 
('Alpina B8 Gran Coupe'), 
('Alpina XB7'), 
('i3'), 
('i3 (94Ah)'), 
('i3 (94Ah) with Range Extender'), 
('i3 BEV'), 
('i3 BEV (60  Amp-hour battery)'), 
('i3 BEV (94 Amp-hour battery)'), 
('i3 REX'), 
('i3 REX  (94 Amp-hour battery)'), 
('i3 with Range Extender'), 
('i3s'), 
('i3s (94Ah)'), 
('i3s (94Ah) with Range Extender'), 
('i3s with Range Extender'), 
('i4 eDrive35 Gran Coupe'), 
('i4 eDrive40 Gran Coupe'), 
('i4 M50 Gran Coupe'), 
('i4 xDrive40 Gran Coupe'), 
('i5 eDrive40 Sedan'), 
('i5 M60 xDrive Sedan'), 
('i7 eDrive50 Sedan'), 
('i7 M70 xDrive Sedan'), 
('i7 xDrive60 Sedan'), 
('i8'), 
('I8 Coupe'), 
('I8 Roadster'), 
('iX M60'), 
('iX xDrive40'), 
('iX xDrive50'), 
('M Coupe'), 
('M Roadster'), 
('M1 Coupe'), 
('M2'), 
('M2 Competition'), 
('M2 Competition Coupe'), 
('M2 Coupe'), 
('M2 CS Coupe'), 
('M235i'), 
('M235i Convertible'), 
('M235i xDrive'), 
('M235i xDrive Convertible'), 
('M235i xDrive Gran Coupe'), 
('M240i Convertible'), 
('M240i Coupe'), 
('M240i Coupe M Performance'), 
('M240i xDrive Convertible'), 
('M240i xDrive Coupe'), 
('M240i xDrive Coupe M Performance'), 
('M3'), 
('M3 Competition'), 
('M3 Competition M xDrive Sedan'), 
('M3 Competition Sedan'), 
('M3 Convertible'), 
('M3 Coupe'), 
('M3 CS'), 
('M3 CS Sedan'), 
('M3 Sedan'), 
('M340i'), 
('M340i Sedan'), 
('M340i xDrive'), 
('M340i xDrive Sedan'), 
('M4 Competition Coupe'), 
('M4 Competition M xDrive Convertible'), 
('M4 Competition M xDrive Coupe'), 
('M4 Convertible'), 
('M4 Convertible Competition'), 
('M4 Coupe'), 
('M4 Coupe Competition'), 
('M4 CS'), 
('M4 CSL Coupe'), 
('M4 DTM Champions Edition'), 
('M4 GTS'), 
('M440i Convertible'), 
('M440i Coupe'), 
('M440i Gran Coupe'), 
('M440i xDrive Convertible'), 
('M440i xDrive Coupe'), 
('M440i xDrive Gran Coupe'), 
('M5'), 
('M5 Competition'), 
('M5 Competition Sedan'), 
('M5 CS Sedan'), 
('M5 Sedan'), 
('M550i xDrive'), 
('M550i xDrive Sedan'), 
('M6'), 
('M6 Convertible'), 
('M6 Coupe'), 
('M6 Gran Coupe'), 
('M760i xDrive'), 
('M760i xDrive Sedan'), 
('M8 Competition Convertible'), 
('M8 Competition Coupe'), 
('M8 Competition Gran Coupe'), 
('M8 Convertible'), 
('M8 Coupe'), 
('M8 Gran Coupe'), 
('M850i xDrive Convertible'), 
('M850i xDrive Coupe'), 
('M850i xDrive Gran Coupe'), 
('X1 M35i'), 
('X1 sDrive28i'), 
('X1 xDrive28i'), 
('X1 xDrive35i'), 
('X2 M35i'), 
('X2 sDrive28i'), 
('X2 xDrive28i'), 
('X3'), 
('X3 3.0i'), 
('X3 3.0si'), 
('X3 M'), 
('X3 M Competition'), 
('X3 M40i'), 
('X3 sDrive 28i'), 
('X3 sDrive28i'), 
('X3 sDrive30i'), 
('X3 xDrive28d'), 
('X3 xDrive28i'), 
('X3 xDrive30e'), 
('X3 xDrive30i'), 
('X3 xDrive35i'), 
('X4 M'), 
('X4 M Competition'), 
('X4 M40i'), 
('X4 xDrive28i'), 
('X4 xDrive30i'), 
('X4 xDrive35i'), 
('X5'), 
('X5 3.0si'), 
('X5 4.6is'), 
('X5 4.8i'), 
('X5 4.8IS'), 
('X5 M'), 
('X5 M Competition'), 
('X5 M50i'), 
('X5 M60i xDrive'), 
('X5 sDrive35i'), 
('X5 sDrive40i'), 
('X5 xDrive 35d'), 
('X5 xDrive30i'), 
('X5 xDrive35d'), 
('X5 xDrive35i'), 
('X5 xDrive40e'), 
('X5 xDrive40i'), 
('X5 xDrive45e'), 
('X5 xDrive48i'), 
('X5 xDrive50i'), 
('X5 xDriveM'), 
('X6 M'), 
('X6 M Competition'), 
('X6 M50i'), 
('X6 M60i xDrive'), 
('X6 sDrive35i'), 
('X6 sDrive40i'), 
('X6 xDrive35i'), 
('X6 xDrive40i'), 
('X6 xDrive50i'), 
('X6 xDriveM'), 
('X7 M50i'), 
('X7 M60i xDrive'), 
('X7 xDrive40i'), 
('X7 xDrive50i'), 
('XM'), 
('Z3 Coupe'), 
('Z3 Roadster'), 
('Z4 3.0i'), 
('Z4 3.0Si'), 
('Z4 3.0Si Coupe'), 
('Z4 Coupe'), 
('Z4 M Coupe'), 
('Z4 M Roadster'), 
('Z4 M40i'), 
('Z4 Roadster'), 
('Z4 sDrive28i'), 
('Z4 sDrive30i'), 
('Z4 sDrive35i'), 
('Z4 sDrive35is'), 
('Z8'), 
('B7'), 
('Roadster V8'), 
('Chiron'), 
('Chiron Pur Sport'), 
('Chiron Super Sport'), 
('Divo'), 
('Veyron'), 
('Cascada'), 
('Century'), 
('Century Estate Wagon'), 
('Century Wagon'), 
('Coachbuilder Wagon'), 
('Electra Estate Wagon'), 
('Electra/Park Avenue'), 
('Enclave AWD'), 
('Enclave FWD'), 
('Encore'), 
('Encore AWD'), 
('Encore FWD'), 
('Encore GX AWD'), 
('Encore GX FWD'), 
('Envision AWD'), 
('Envision FWD'), 
('Envista'), 
('Estate Wagon'), 
('Funeral Coach/Hearse'), 
('LaCrosse'), 
('LaCrosse AWD'), 
('LaCrosse eAssist'), 
('Lacrosse/Allure'), 
('Lacrosse/Allure AWD'), 
('LeSabre'), 
('LeSabre/Electra Wagon'), 
('Lucerne'), 
('Park Avenue'), 
('Rainier 2WD'), 
('Rainier AWD'), 
('Reatta'), 
('Regal'), 
('Regal AWD'), 
('Regal eAssist'), 
('Regal TourX AWD'), 
('Regal/Century'), 
('Rendezvous AWD'), 
('Rendezvous FWD'), 
('Riviera'), 
('Riviera Convertible'), 
('Roadmaster'), 
('Roadmaster Wagon'), 
('Skyhawk'), 
('Skyhawk Wagon'), 
('Skylark'), 
('Somerset Regal'), 
('Somerset/Skylark'), 
('Terraza AWD'), 
('Terraza FWD'), 
('Verano'), 
('e6'), 
('Allante'), 
('Armored Deville'), 
('Armored DTS'), 
('ATS'), 
('ATS AWD'), 
('ATS-V'), 
('Brougham'), 
('Brougham/DeVille (RWD)'), 
('Catera'), 
('Cimarron'), 
('Commercial Chassis'), 
('CT4'), 
('CT4 AWD'), 
('CT4 V'), 
('CT4 V AWD'), 
('CT5'), 
('CT5 AWD'), 
('CT5 V'), 
('CT5 V AWD'), 
('CT6'), 
('CT6 AWD'), 
('CT6 Plug-In'), 
('CTS'), 
('CTS AWD'), 
('CTS Sedan'), 
('CTS Sedan AWD'), 
('CTS V'), 
('CTS Wagon'), 
('CTS Wagon AWD'), 
('CTS-V'), 
('DeVille'), 
('DeVille/60 Special'), 
('DeVille/Concourse'), 
('DTS'), 
('Eldorado'), 
('Eldorado Convertible'), 
('ELR'), 
('ELR Sport'), 
('Escalade 2WD'), 
('Escalade 4WD'), 
('Escalade AWD'), 
('Escalade ESV 2WD'), 
('Escalade ESV 4WD'), 
('Escalade ESV AWD'), 
('Escalade Ext AWD'), 
('Escalade Hybrid 2WD'), 
('Escalade Hybrid 4WD'), 
('Escalade V 4WD'), 
('Escalade V AWD'), 
('Fleetwood'), 
('Fleetwood Brougham'), 
('Fleetwood Brougham (RWD)'), 
('Fleetwood/DeVille'), 
('Fleetwood/DeVille (FWD)'), 
('Funeral Coach / Hearse'), 
('Limousine'), 
('LYRIQ'), 
('LYRIQ AWD'), 
('Seville'), 
('SRX'), 
('SRX 2WD'), 
('SRX AWD'), 
('STS'), 
('STS 2WD'), 
('STS AWD'), 
('STS-V'), 
('XLR'), 
('XLR-V'), 
('XT4 AWD'), 
('XT4 FWD'), 
('XT5'), 
('XT5 AWD'), 
('XT5 FWD'), 
('XT5 Hearse AWD'), 
('XT5 Hearse FWD'), 
('XT5 Limo AWD'), 
('XT5 Limo FWD'), 
('XT6 AWD'), 
('XT6 FWD'), 
('XTS'), 
('XTS AWD'), 
('XTS Hearse'), 
('XTS Limo'), 
('Duntov GT'), 
('Astro 2WD (cargo)'), 
('Astro 2WD (cargo) Conversion'), 
('Astro 2WD (passenger)'), 
('Astro AWD (cargo)'), 
('Astro AWD (cargo) Conversion'), 
('Astro AWD (passenger)'), 
('Avalanche 1500 2WD'), 
('Avalanche 1500 4WD'), 
('Avalanche 1500 AWD'), 
('Aveo'), 
('Aveo 5'), 
('Beretta'), 
('Blazer 1500 4WD'), 
('Blazer 2WD'), 
('Blazer 4WD'), 
('Blazer AWD'), 
('Blazer FWD'), 
('Blazer V1500 4WD'), 
('Bolt EUV'), 
('Bolt EV'), 
('C10 Pickup 2WD'), 
('C1500 Pickup 2WD'), 
('C20 Pickup 2WD'), 
('C2500 Pickup 2WD'), 
('Camaro'), 
('Caprice'), 
('Caprice Wagon'), 
('Caprice/Impala'), 
('Caprice/Impala Wagon'), 
('Captiva AWD'), 
('Captiva FWD'), 
('Cavalier'), 
('Cavalier (Bi-fuel CNG)'), 
('Cavalier Convertible'), 
('Cavalier Dual-fuel'), 
('Cavalier Wagon'), 
('Celebrity'), 
('Celebrity Wagon'), 
('Chevette'), 
('Chevette CS'), 
('Citation II'), 
('City Express Cargo Van'), 
('Classic'), 
('Cobalt'), 
('Cobalt Coupe'), 
('Cobalt Sedan'), 
('Cobalt SS Coupe'), 
('Cobalt XFE'), 
('Cobalt XFE Coupe'), 
('Cobalt XFE Sedan'), 
('Colorado 2WD'), 
('Colorado 4WD'), 
('Colorado Cab Chassis 2WD'), 
('Colorado Cab Chassis inc 2WD'), 
('Colorado Cab Chassis inc 4WD'), 
('Colorado Crew Cab 2WD'), 
('Colorado Crew Cab 4WD'), 
('Colorado Mud Terrain Tires 4WD'), 
('Colorado ZR2 4WD'), 
('Corsica'), 
('Corvette'), 
('Corvette Convertible'), 
('Corvette Z06'), 
('Corvette Z06 Carbon Aero'), 
('Corvette ZR1'), 
('Cruze'), 
('Cruze Eco'), 
('Cruze HaTChback'), 
('Cruze Limited'), 
('Cruze Limited  Eco'), 
('Cruze Premier'), 
('Cruze Premier HaTChback'), 
('El Camino Pickup 2WD'), 
('Epica'), 
('Equinox AWD'), 
('Equinox FWD'), 
('Express 1500 2WD Cargo'), 
('Express 1500 2WD Conversion Cargo'), 
('Express 1500 2WD Passenger'), 
('Express 1500 AWD'), 
('Express 1500 AWD Cargo'), 
('Express 1500 AWD Conversion Cargo');