INSERT INTO VehicleModels (Model)
VALUES
('Express 1500 AWD Passenger'), 
('Express 1500/2500 2WD'), 
('Express 2500 2WD Cargo'), 
('Express 2500 2WD Conversion Cargo'), 
('Express 2500 2WD Passenger'), 
('Express 3500 2WD Cargo'), 
('Express 3500 2WD Passenger'), 
('Express Cargo (Bi-fuel)'), 
('Express Cargo (dedicated CNG)'), 
('Express Passenger (Bi-fuel)'), 
('Express Passenger (dedicated CNG)'), 
('G10/20 Sport Van 2WD'), 
('G10/20 Van 2WD'), 
('G10/20 Van 2WD (cargo)'), 
('G30 Sport Van 2WD'), 
('G30 Van 2WD'), 
('G30 Van 2WD (cargo)'), 
('HHR FWD'), 
('HHR Panel FWD'), 
('Impala'), 
('Impala Bi-Fuel  (CNG)'), 
('Impala eAssist'), 
('Impala Limited'), 
('Impala Police'), 
('Impala/Caprice'), 
('K10 Blazer 4WD'), 
('K10 Pickup 4WD'), 
('K1500 Pickup 4WD'), 
('K20 Pickup 4WD'), 
('K2500 Pickup 4WD'), 
('K5/K10 Blazer 4WD'), 
('Lumina'), 
('Lumina Minivan 2WD'), 
('Lumina/APV Minivan 2WD'), 
('Lumina/Monte Carlo'), 
('Malibu'), 
('Malibu eAssist'), 
('Malibu Hybrid'), 
('Malibu Limited'), 
('Malibu Maxx'), 
('Metro'), 
('Monte Carlo'), 
('Nova'), 
('Optra'), 
('Optra 5'), 
('Optra Wagon'), 
('Pickup 2500 2WD'), 
('Pickup 2500 4WD'), 
('Postal Cab Chassis 2WD'), 
('Prizm'), 
('R10 Pickup 2WD'), 
('R10 Suburban 2WD'), 
('R1500 Suburban 2WD'), 
('R20 (C20) Pickup 2WD'), 
('S10 Blazer 2WD'), 
('S10 Blazer 4WD'), 
('S10 Cab Chassis 2WD'), 
('S10 Electric'), 
('S10 Pickup 2WD'), 
('S10 Pickup 2WD FFV'), 
('S10 Pickup 4WD'), 
('S10 Utility Body 2WD'), 
('Silverado 15 Hybrid 2WD'), 
('Silverado 15 Hybrid 4WD'), 
('Silverado 1500 2WD'), 
('Silverado 1500 4WD'), 
('Silverado 1500 AWD'), 
('Silverado 2500 2WD'), 
('Silverado 2500 2WD (Bifuel)'), 
('Silverado 2500 HD 2WD'), 
('Silverado 2500 HD 2WD CNG'), 
('Silverado 2500 HD 4WD CNG'), 
('Silverado 2WD'), 
('Silverado 4WD'), 
('Silverado 4WD TrailBoss'), 
('Silverado 4WD ZR2'), 
('Silverado C10 2WD'), 
('Silverado C10 Cab Chassis 2WD'), 
('Silverado C10 XFE 2WD'), 
('Silverado C15 2WD'), 
('Silverado C15 Cab Chassis 2WD'), 
('Silverado C15 XFE 2WD'), 
('Silverado Cab Chassis 2WD'), 
('Silverado Cab Chassis 4WD'), 
('Silverado Classic 15 Hybrid 2WD'), 
('Silverado Classic 15 Hybrid 4WD'), 
('Silverado Classic 1500 2WD'), 
('Silverado Classic 1500 4WD'), 
('Silverado EV'), 
('Silverado K10 4WD'), 
('Silverado K10 4WD TrailBoss'), 
('Silverado K10 Cab Chassis 4WD'), 
('Silverado K15 4WD'), 
('Silverado K15 Cab Chassis 4WD'), 
('Silverado LD C15 2WD'), 
('Silverado LD K15 4WD'), 
('Silverado Mud Terrain Tires 4WD'), 
('Silverado SS 1500 AWD'), 
('Sonic'), 
('Sonic 5'), 
('Sonic 5 RS'), 
('Sonic RS'), 
('Spark'), 
('Spark ACTIV'), 
('Spark EV'), 
('Spectrum'), 
('Spectrum Turbo'), 
('Sport Van G10/20 2WD'), 
('Sport Van G10/20 2WD (passenger)'), 
('Sport Van G30  2WD'), 
('Sport Van G30 2WD'), 
('Sport Van G30 2WD (cargo)'), 
('Sprint'), 
('Sprint ER'), 
('Sprint Metro'), 
('Sprint Plus'), 
('SS'), 
('SSR Pickup 2WD'), 
('Suburban 1500 2WD'), 
('Suburban 1500 4WD'), 
('Suburban 1500 AWD'), 
('Suburban 2500 2WD'), 
('Suburban 2500 4WD'), 
('Suburban 2WD'), 
('Suburban 4WD'), 
('Suburban C10 2WD'), 
('Suburban C1500 2WD'), 
('Suburban K10 4WD'), 
('Suburban K1500 4WD'), 
('Suburban V1500 4WD'), 
('T10 (S10) Blazer 4WD'), 
('T10 (S10) Pickup 4WD'), 
('Tahoe 1500 2WD'), 
('Tahoe 1500 4WD'), 
('Tahoe 1500 AWD'), 
('Tahoe 1500 XFE 2WD'), 
('Tahoe 2WD'), 
('Tahoe 4WD'), 
('Tahoe C10 2WD'), 
('Tahoe C1500 2WD'), 
('Tahoe Hybrid 2WD'), 
('Tahoe Hybrid 4WD'), 
('Tahoe K10 4WD'), 
('Tahoe K1500 4WD'), 
('Tracker 2WD Convertible'), 
('Tracker 2WD Hardtop'), 
('Tracker 4WD Convertible'), 
('Tracker 4WD Hardtop'), 
('Tracker LT 2WD'), 
('Tracker LT 4WD'), 
('Tracker ZR2 4WD'), 
('Tracker ZR2 4WD Convertible'), 
('Trailblazer 2WD'), 
('Trailblazer 4WD'), 
('Trailblazer AWD'), 
('Trailblazer EXT 2WD'), 
('Trailblazer EXT 4WD'), 
('Trailblazer FWD'), 
('Traverse AWD'), 
('Traverse FWD'), 
('Trax'), 
('Trax AWD'), 
('Trax FWD'), 
('Turbo Sprint'), 
('Twin-Turbo Corvette'), 
('Uplander AWD'), 
('Uplander FWD'), 
('V10 (K10) Blazer 4WD'), 
('V10 (K10) Pickup 4WD'), 
('V10 (K10) Suburban 4WD'), 
('V10 Blazer 4WD'), 
('V10 Suburban 4WD'), 
('V20 Pickup 4WD'), 
('Van 15/25  2WD Conversion'), 
('Van 15/25 2WD Conversion'), 
('Van 1500 2WD Cargo'), 
('Van 1500 2WD Conversion Cargo'), 
('Van 1500 AWD Cargo'), 
('Van 1500 AWD Conversion'), 
('Van 1500 AWD Conversion Cargo'), 
('Van 1500/2500 2WD'), 
('Van 1500/2500 AWD'), 
('Venture 2WD'), 
('Venture AWD'), 
('Venture FWD'), 
('Volt'), 
('300'), 
('200 AWD'), 
('200 Convertible'), 
('300 AWD'), 
('300 M'), 
('300 SRT8'), 
('300/SRT-8'), 
('300C AWD'), 
('300C/SRT-8'), 
('Aspen 2WD'), 
('Aspen 4WD'), 
('Aspen HEV'), 
('Cirrus'), 
('Concorde'), 
('Concorde/LHS'), 
('Conquest'), 
('Crossfire'), 
('Crossfire Coupe'), 
('Crossfire Roadster'), 
('E Class/New Yorker'), 
('Executive Sedan/Limousine'), 
('Fifth Avenue/Imperial'), 
('Imperial/New Yorker Fifth Avenue'), 
('JX/JXI/Limited Convertible'), 
('Laser'), 
('Laser/Daytona'), 
('LeBaron'), 
('LeBaron Convertible'), 
('LeBaron GTS'), 
('LeBaron Landau'), 
('LHS'), 
('New Yorker'), 
('New Yorker Fifth Avenue/Imperial'), 
('New Yorker Turbo'), 
('New Yorker/5th Avenue'), 
('New Yorker/LHS'), 
('Newport/Fifth Avenue'), 
('Pacifica'), 
('Pacifica 2WD'), 
('Pacifica AWD'), 
('Pacifica FWD'), 
('Pacifica Hybrid'), 
('Prowler'), 
('PT Cruiser'), 
('PT Cruiser Convertible'), 
('QC Car'), 
('Sebring'), 
('Sebring 4 Door'), 
('Sebring AWD'), 
('Sebring Convertible'), 
('TC By'), 
('TC By Convertible'), 
('TC by Maserati'), 
('Town and Country'), 
('Town and Country 2WD'), 
('Town and Country 4WD'), 
('Town and Country AWD'), 
('Town and Country Wagon'), 
('Town and Country/Voyager/Grand Voy. 2WD'), 
('Town and Country/Voyager/Grand Voy. AWD'), 
('Voyager'), 
('Voyager/Town and Country 2WD'), 
('CODA'), 
('Consulier GTP'), 
('CX 25 GTI'), 
('CX 25 Prestige'), 
('CX 25Tri'), 
('Cxestate'), 
('XM v6'), 
('XM v6 Break'), 
('XM v6a'), 
('WB'), 
('Coupe'), 
('Sedan'), 
('Station Wagon'), 
('Kalos'), 
('Lacetti'), 
('Lanos'), 
('Leganza'), 
('Magnus'), 
('Nubira'), 
('Nubira Station Wagon'), 
('Nubira Wagon'), 
('Charade'), 
('Charade E'), 
('Rocky 4WD'), 
('600'), 
('600 Convertible'), 
('AD100/AD150 Ramcharger 2WD'), 
('Aries'), 
('Aries Wagon'), 
('Avenger'), 
('Avenger AWD'), 
('AW100/AW150 Ramcharger 4WD'), 
('B150/B250 Van 2WD'), 
('B150/B250 Wagon 2WD'), 
('B1500 Van 2WD'), 
('B1500 Wagon 2WD'), 
('B1500/B2500 Van 2WD'), 
('B1500/B2500 Wagon 2WD'), 
('B2500 Van 2WD'), 
('B2500 Wagon 2WD'), 
('B350 Van 2WD'), 
('B350 Wagon 2WD'), 
('B3500 Van 2WD'), 
('B3500 Wagon 2WD'), 
('Caliber'), 
('Caliber AWD'), 
('Caravan C/V/Grand Caravan 2WD'), 
('Caravan C/V/Grand Caravan 4WD'), 
('Caravan/Grand Caravan 2WD'), 
('Caravan/Grand Caravan 4WD'), 
('Caravan/Grand Caravan AWD'), 
('Caravan/Grand Caravan FWD'), 
('Caravan/Grand Caravan/Ram Van 2WD'), 
('Caravan/Ram Van 2WD'), 
('Challenger'), 
('Challenger AWD'), 
('Challenger GT'), 
('Challenger SRT'), 
('Challenger SRT Widebody'), 
('Challenger SRT8'), 
('Challenger Widebody'), 
('Charger'), 
('Charger AWD'), 
('Charger GLH-S'), 
('Charger SRT'), 
('Charger SRT Widebody'), 
('Charger SRT8'), 
('Charger Widebody'), 
('Colt'), 
('Colt Vista'), 
('Colt Vista 4WD'), 
('Colt Wagon'), 
('Colt Wagon 4WD'), 
('CSX'), 
('D100/D150 Pickup 2WD'), 
('D250 Cab Chassis 2WD'), 
('D250 Pickup 2WD'), 
('D250 Pickup Cab Chassis 2WD'), 
('Dakota Cab Chassis 2WD'), 
('Dakota Pickup 2WD'), 
('Dakota Pickup 4WD'), 
('Dart'), 
('Dart Aero'), 
('Dart GT'), 
('Daytona'), 
('Diplomat'), 
('Durango 2WD'), 
('Durango 4WD'), 
('Durango AWD'), 
('Durango HEV'), 
('Durango RWD'), 
('Durango SRT AWD'), 
('Dynasty'), 
('GLH-S'), 
('Grand Caravan'), 
('Hornet AWD'), 
('Intrepid'), 
('Journey'), 
('Journey  2WD'), 
('Journey  4WD'), 
('Journey  AWD'), 
('Journey AWD'), 
('Journey FWD'), 
('Lancer'), 
('Lancer Convertible'), 
('Magnum'), 
('Magnum 2WD'), 
('Magnum AWD'), 
('Monaco'), 
('Neon'), 
('Neon/SRT-4/SX 2.0'), 
('Nitro 2WD'), 
('Nitro 4WD'), 
('Omni'), 
('Power Ram 50 4WD'), 
('Power Ram 50 Pickup 4WD'), 
('Power Ram50 4WD'), 
('Raider'), 
('Raider 4WD'), 
('Ram 1500 Pickup 2WD'), 
('Ram 1500 Pickup 4WD'), 
('Ram 2500 Pickup 2WD'), 
('Ram 2500 Pickup 4WD'), 
('Ram 50 Pickup 2WD'), 
('Ram Van 1500 2WD'), 
('Ram Van 2500 2WD'), 
('Ram Van 2500 2WD CNG'), 
('Ram Wagon 1500 2WD'), 
('Ram Wagon 2500 2WD'), 
('Ram Wagon 2500 2WD CNG'), 
('Ramcharger 2WD'), 
('Ramcharger 4WD'), 
('Rampage Pickup 2WD'), 
('Shadow'), 
('Shadow Convertible'), 
('Spirit'), 
('Stealth'), 
('Stratus'), 
('Stratus 4 Door'), 
('Viper'), 
('Viper Convertible'), 
('Viper Coupe'), 
('Viper SRT'), 
('W100/W150 Pickup 4WD'), 
('W250 Pickup 4WD'), 
('Funeral Coach'), 
('Medallion Sedan'), 
('Medallion Wagon'), 
('Premier'), 
('Renault Medallion Sedan'), 
('Renault Medallion Wagon'), 
('Summit'), 
('Summit Wagon'), 
('Talon'), 
('Vision'), 
('Wagon 4WD'), 
('ERD 1'), 
('Series 1'), 
('Series I'), 
('Phaeton'), 
('24E'), 
('85J'), 
('Formal'), 
('Heritage'), 
('Lincoln 100J'), 
('Lincoln 24E'), 
('Lincoln 85J'), 
('Lincoln Eagle/Windsor'), 
('Lincoln Eaton'), 
('Lincoln Stratford'), 
('Renaissance'), 
('Six Door'), 
('Windsor'), 
('308'), 
('575'), 
('296 GTB'), 
('3.2 Mondial/Cabriolet'), 
('328 GTS/GTB'), 
('348 TB/TS'), 
('360 Modena/Modena F1'), 
('360 Modena/Spider'), 
('360 Modena/Spider/Challenge'), 
('456 MGT/MGA'), 
('458 Italia'), 
('458 Italia Coupe'), 
('458 Italia Spider'), 
('458 Speciale'), 
('458 Speciale Spider'), 
('458 Spider'), 
('488 GTB'), 
('488 Pista'), 
('488 Pista Spider'), 
('488 Spider'), 
('550 Maranello'), 
('550 Maranello/Barchetta'), 
('575 M Maranello'), 
('575 M Maranello and Superamerica'), 
('599 GTB'), 
('599 GTB Fiorano'), 
('599 GTO'), 
('599 SA Aperta'), 
('612 Scaglietti'), 
('812 Competizione'), 
('812 Competizione A'), 
('812 GTS'), 
('812 Superfast'), 
('California'), 
('California T'), 
('Daytona SP3'), 
('Enzo Ferrari'), 
('F 40'), 
('F12'), 
('F12 Berlinetta'), 
('F12 tdf'), 
('F141'), 
('F355/355 F1'), 
('F40'), 
('F430'), 
('F60 America'), 
('F8 Spider'), 
('F8 Tributo'), 
('Ferrari 348 TB/TS'), 
('Ferrari 348 TB/TS/Spider'), 
('Ferrari 456'), 
('Ferrari 456 GT'), 
('Ferrari 456 GT/GTA'), 
('Ferrari 512 TR'), 
('Ferrari 550 Maranello'), 
('Ferrari F355'), 
('Ferrari F355 Berlinetta/GTS'), 
('Ferrari F355/355 F1'), 
('Ferrari F50'), 
('Ferrari F512M'), 
('Ferrari Mondial T/Cabriolet'), 
('FF'), 
('GTC4Lusso'), 
('GTC4Lusso T'), 
('LaFerrari Aperta'), 
('LaFerrari Hybrid'), 
('Mondial'), 
('Mondial T/Cabriolet'), 
('Mondial/Cabriolet'), 
('Monza SP1'), 
('Monza SP2'), 
('Portofino'), 
('Portofino M'), 
('Roma'), 
('SF90 Spider'), 
('SF90 Stradale'), 
('SF90 Stradale Coupe'), 
('Testarossa'), 
('500'), 
('124 Spider'), 
('500 Abarth'), 
('500 Cabrio'), 
('500 L'), 
('500 X'), 
('500 X AWD'), 
('500e'), 
('500X AWD'), 
('Karma'), 
('Ocean Extreme One'), 
('Aerostar Van'), 
('Aerostar Van AWD'), 
('Aerostar Wagon'), 
('Aerostar Wagon AWD'), 
('Aspire'), 
('Bronco 4WD'), 
('Bronco Badlands 4WD'), 
('Bronco Black Diamond 4WD'), 
('Bronco II 2WD'), 
('Bronco II 4WD'), 
('Bronco Raptor 4WD'), 
('Bronco SasquaTCh 4WD'), 
('Bronco Sport 4WD'), 
('C-MAX Energi Plug-in Hybrid'), 
('C-MAX Hybrid FWD'), 
('Contour'), 
('Courier'), 
('Courier Pickup 2WD'), 
('Courier Pickup 4WD'), 
('Crown Victoria'), 
('Crown Victoria CNG'), 
('Crown Victoria FFV'), 
('Crown Victoria Police'), 
('E150 Club Wagon'), 
('E150 Club Wagon 2WD'), 
('E150 Econoline 2WD'), 
('E150 Van FFV'), 
('E150 Wagon FFV'), 
('E250 CNG'), 
('E250 Econoline 2WD'), 
('E250 Econoline 2WD CNG'), 
('E250 Van FFV'), 
('E350 Van'), 
('E350 Van FFV'), 
('E350 Wagon'), 
('E350 Wagon FFV'), 
('EcoSport AWD'), 
('EcoSport FWD'), 
('Edge AWD'), 
('Edge FWD'), 
('Escape 2WD'), 
('Escape 4WD'), 
('Escape 4WD FFV'), 
('Escape AWD'), 
('Escape AWD FFV'), 
('Escape AWD HEV'), 
('Escape FWD'), 
('Escape FWD FFV'), 
('Escape FWD HEV'), 
('Escape FWD PHEV'), 
('Escape Hybrid 2WD'), 
('Escape Hybrid 4WD'), 
('Escape Hybrid AWD'), 
('Escape Hybrid FWD'), 
('Escort'), 
('Escort FS'), 
('Escort Wagon'), 
('Escort ZX2'), 
('EXP'), 
('Expedition 2WD'), 
('Expedition 2WD FFV'), 
('Expedition 4WD'), 
('Expedition 4WD FFV'), 
('Expedition EL 2WD'), 
('Expedition EL 4WD'), 
('Expedition Limo. 2WD FFV'), 
('Expedition MAX 2WD'), 
('Expedition MAX 4WD'), 
('Expedition Timberline AWD'), 
('Explorer 2WD'), 
('Explorer 2WD FFV'), 
('Explorer 4WD'), 
('Explorer 4WD FFV'), 
('Explorer AWD'), 
('Explorer AWD FFV'), 
('Explorer FFV AWD'), 
('Explorer FWD'), 
('Explorer HEV AWD'), 
('Explorer HEV RWD'), 
('Explorer Platinum HEV AWD'), 
('Explorer Platinum HEV RWD'), 
('Explorer RWD'), 
('Explorer Sport 2WD'), 
('Explorer Sport 2WD FFV'), 
('Explorer Sport 4WD'), 
('Explorer Sport 4WD FFV'), 
('Explorer Sport Trac 2WD'), 
('Explorer Sport Trac 2WD FFV'), 
('Explorer Sport Trac 4WD'), 
('Explorer Sport Trac 4WD FFV'), 
('Explorer Timberline AWD'), 
('Explorer USPS 2WD'), 
('Explorer USPS 2WD FFV'), 
('Explorer USPS 4WD'), 
('Explorer USPS 4WD FFV'), 
('Explorer USPS Electric'), 
('F150 2.7L 2WD GVWR>6649 LBS'), 
('F150 2.7L 2WD GVWR>6649 LBS PAYLOAD PACKAGE'), 
('F150 2.7L 4WD GVWR>6799 LBS'), 
('F150 2.7L 4WD GVWR>6799 LBS PAYLOAD PACKAGE'), 
('F150 2WD BASE PAYLOAD LT TIRE'), 
('F150 2WD FFV BASE PAYLOAD LT'), 
('F150 2WD FFV BASE PAYLOAD LT TIRE'), 
('F150 3.5L 2WD GVWR>7599 LBS'), 
('F150 3.5L 2WD GVWR>7599 LBS PAYLOAD PACKAGE'), 
('F150 3.5L 4WD GVWR>7599 LBS'), 
('F150 3.5L 4WD GVWR>7599 LBS PAYLOAD PACKAGE'), 
('F150 4WD BASE PAYLOAD LT TIRE'), 
('F150 4WD FFV BASE PAYLOAD LT'), 
('F150 4WD FFV BASE PAYLOAD LT TIRE'), 
('F150 5.0L 2WD FFV GVWR>7599 LBS'), 
('F150 5.0L 2WD FFV GVWR>7599 LBS PAYLOAD PACKAGE'), 
('F150 5.0L 2WD GVWR>7599 LBS'), 
('F150 5.0L 4WD FFV GVWR>7599 LBS'), 
('F150 5.0L 4WD FFV GVWR>7599 LBS PAYLOAD PACKAGE'), 
('F150 5.0L 4WD GVWR>7599 LBS'), 
('F150 CNG'), 
('F150 Dual-fuel 2WD (CNG)'), 
('F150 Dual-fuel 2WD (LPG)'), 
('F150 Dual-fuel 4WD (CNG)'), 
('F150 Dual-fuel 4WD (LPG)'), 
('F-150 Lightning 4WD'), 
('F-150 Lightning 4WD Extended Range'), 
('F-150 Lightning Platinum 4WD'), 
('F150 Pickup 2WD'), 
('F150 Pickup 2WD CNG'), 
('F150 Pickup 2WD FFV'), 
('F150 Pickup 2WD HEV'), 
('F150 Pickup 2WD Limited'), 
('F150 Pickup 4WD'), 
('F150 Pickup 4WD FFV'), 
('F150 Pickup 4WD HEV'), 
('F150 Pickup 4WD Limited'), 
('F150 Pickup 4WD XL/XLT'), 
('F150 Pickup Tremor 4WD'), 
('F150 Pickup Tremor 4WD FFV'), 
('F150 RAPTOR 37 4WD'), 
('F150 RAPTOR 4WD'), 
('F150 Raptor Pickup 4WD'), 
('F150 RAPTOR R 4WD'), 
('F150 SFE 2WD'), 
('F150 STX SE 2WD'), 
('F150 STX SE 2WD FFV'), 
('F250'), 
('F250 Pickup 2WD'), 
('F250 Pickup 2WD CNG'), 
('F250 Pickup 4WD'), 
('F250 Pickup Cab Chassis 2WD'), 
('Festiva'), 
('Fiesta'), 
('Fiesta FWD'), 
('Fiesta SFE'), 
('Fiesta SFE FWD'), 
('Fiesta ST FWD'), 
('Five Hundred AWD'), 
('Five Hundred FWD'), 
('Flex AWD'), 
('Flex FWD'), 
('Focus'), 
('Focus Electric'), 
('Focus FWD'), 
('Focus FWD FFV'), 
('Focus RS AWD'), 
('Focus SFE FWD'), 
('Focus SFE FWD FFV'), 
('Focus ST FWD'), 
('Focus Station Wagon'), 
('Freestar Cargo Van FWD'), 
('Freestar Wagon FWD'), 
('Freestyle AWD'), 
('Freestyle FWD'), 
('Fusion'), 
('Fusion AWD'), 
('Fusion AWD FFV'), 
('Fusion Energi Plug-in Hybrid'), 
('Fusion FWD'), 
('Fusion FWD FFV'), 
('Fusion Hybrid FWD'), 
('Fusion Hybrid Taxi'), 
('Fusion S FWD'), 
('Fusion Special Service PHEV'), 
('Fusion Special Service Vehicle PHEV'), 
('GT'), 
('GT 2WD'), 
('Lightning F150 2WD'), 
('Lightning Pickup 2WD'), 
('LTD'), 
('LTD Crown Victoria'), 
('LTD Crown Victoria Wagon'), 
('LTD Crown Victoria/Country Squire Wagon'), 
('LTD Wagon'), 
('Maverick AWD'), 
('Maverick FWD'), 
('Maverick HEV FWD'), 
('Maverick Tremor AWD'), 
('Mustang'), 
('Mustang Bullitt'), 
('Mustang Convertible'), 
('Mustang Dark Horse'), 
('Mustang HO Convertible'), 
('Mustang HO Coupe'), 
('Mustang Mach 1'), 
('Mustang Mach-E AWD'), 
('Mustang Mach-E AWD Extended'), 
('Mustang Mach-E CAL RT 1 ER AWD'), 
('Mustang Mach-E CAL RT 1 ER RWD'), 
('Mustang Mach-E GT'), 
('Mustang Mach-E GT Performance'), 
('Mustang Mach-E RWD'), 
('Mustang Mach-E RWD California Route 1'), 
('Mustang Mach-E RWD Extended'), 
('Mustang Mach-E RWD LFP'), 
('Mustang Performance Package'), 
('Postal Vehicle'), 
('Probe'), 
('Ranger 2WD'), 
('Ranger 2WD FFV'), 
('Ranger 2WD Incomplete'), 
('Ranger 4WD'), 
('Ranger 4WD FFV'), 
('Ranger Pickup 2WD'), 
('Ranger Pickup 4WD'), 
('Ranger Pickup Cab Chassis'), 
('Ranger Pickup Cab Chassis 2WD'), 
('Ranger Tremor 4WD'), 
('Shelby GT350 Mustang'), 
('Shelby GT500 Mustang'), 
('Taurus'), 
('Taurus AWD'), 
('Taurus AWD FFV'), 
('Taurus FFV'), 
('Taurus FWD'), 
('Taurus FWD FFV'), 
('Taurus SHO'), 
('Taurus Wagon'), 
('Taurus Wagon 3.0 A/C'), 
('Taurus Wagon FFV'), 
('Taurus Wagon V6 A/C'), 
('Taurus X AWD'), 
('Taurus X FWD'), 
('Tempo'), 
('Tempo AWD'), 
('Tempo FS'), 
('Th!nk'), 
('Thunderbird'), 
('Transit Connect'), 
('Transit Connect USPS'), 
('Transit Connect Van'), 
('Transit Connect Van 2WD'), 
('Transit Connect Van FFV'), 
('Transit Connect Van FWD'), 
('Transit Connect Wagon FFV'), 
('Transit Connect Wagon FWD'), 
('Transit Connect Wagon LWB FFV'), 
('Transit Connect Wagon LWB FWD'), 
('Transit T150 Wagon'), 
('Transit T150 Wagon 2WD FFV'), 
('Transit T150 Wagon 4WD FFV'), 
('Transit T150 Wagon FFV'), 
('Windstar FWD Cargo Van'), 
('Windstar FWD Van'), 
('Windstar FWD Wagon'), 
('Electrified G80'), 
('Electrified GV70'), 
('G70 AWD'), 
('G70 RWD'), 
('G80 AWD'), 
('G80 RWD'), 
('G90 AWD'), 
('G90 MHEV'), 
('G90 RWD'), 
('GV60 ADVANCE'), 
('GV60 Advanced'), 
('GV60 PERFORMANCE'), 
('GV70 AWD'), 
('GV80 AWD'), 
('GV80 RWD'), 
('Metro LSI'), 
('Metro LSI Convertible'), 
('Metro XFI'), 
('Storm'), 
('Tracker 4WD'), 
('Tracker Convertible 2WD'), 
('Tracker Convertible 4WD'), 
('Tracker Convertible 4x4'), 
('Tracker Hardtop 4WD'), 
('Tracker Van 2WD'), 
('Tracker Van 4WD'), 
('Tracker Van 4x4'), 
('Acadia AWD'), 
('Acadia FWD'), 
('Acadia Limited AWD'), 
('Acadia Limited FWD'), 
('C15 Pickup 2WD'), 
('C15 Suburban 2WD'), 
('C25 Pickup 2WD'), 
('C2500 Sierra 2WD'), 
('Caballero Pickup 2WD'), 
('Canyon 2WD'), 
('Canyon 4WD'), 
('Canyon Cab Chassis 2WD'), 
('Canyon Cab Chassis Inc 2WD'), 
('Canyon Cab Chassis Inc 4WD'), 
('Canyon Crew Cab 2WD'), 
('Canyon Crew Cab 4WD'), 
('Canyon Mud Terrain Tires 4WD'), 
('Envoy 2WD'), 
('Envoy 4WD'), 
('Envoy XL 2WD'), 
('Envoy XL 4WD'), 
('Envoy XUV 2WD'), 
('Envoy XUV 4WD'), 
('EV1'), 
('G15/25 Rally 2WD'), 
('G15/25 Vandura 2WD'), 
('G35 Rally 2WD'), 
('G35 Vandura 2WD'), 
('Hummer EV Pickup'), 
('Hummer EV Pickup MT Tires'), 
('Hummer EV SUV'), 
('Hummer EV SUV MT Tires'), 
('Jimmy 2WD'), 
('Jimmy 4WD'), 
('Jimmy AWD'), 
('Jimmy Sonoma 2WD'), 
('Jimmy Sonoma 4WD'), 
('Jimmy V1500 4WD'), 
('K15 Jimmy 4WD'), 
('K15 Pickup 4WD'), 
('K15 Suburban 4WD'), 
('K25 Pickup 4WD'), 
('K2500 Sierra 4WD'), 
('R15 Pickup 2WD'), 
('R15 Suburban 2WD'), 
('R25 Pickup 2WD'), 
('Rally G15/25 2WD'), 
('Rally G15/25 2WD (passenger)'), 
('Rally G35 2WD'), 
('S15 Cab Chassis 2WD'), 
('S15 Jimmy 2WD'), 
('S15 Jimmy 4WD'), 
('S15 Pickup 2WD'), 
('S15 Pickup 4WD'), 
('S15 Utility Body 2WD'), 
('Safari 2WD (cargo)'), 
('Safari 2WD (Passenger)'), 
('Safari 2WD Conversion (cargo)'), 
('Safari AWD (cargo)'), 
('Safari AWD (Passenger)'), 
('Safari AWD Conversion (cargo)'), 
('Savana (cargo) (Bi-fuel)'), 
('Savana 15/25 2WD Conversion (cargo)'), 
('Savana 15/25 AWD Conversion (cargo)'), 
('Savana 1500  2WD Conversion (cargo)'), 
('Savana 1500  AWD (cargo)'), 
('Savana 1500  AWD Conversion (cargo)'), 
('Savana 1500 2WD (cargo)'), 
('Savana 1500 2WD (Passenger)'), 
('Savana 1500 2WD Conversion (cargo)'), 
('Savana 1500 AWD (cargo)'), 
('Savana 1500 AWD (Passenger)'), 
('Savana 1500 AWD Conversion (cargo)'), 
('Savana 1500/2500  2WD (Passenger)'), 
('Savana 1500/2500 2WD (cargo)'), 
('Savana 1500/2500 2WD (Passenger)'), 
('Savana 1500/2500 AWD (cargo)'), 
('Savana 2500 2WD (cargo)'), 
('Savana 2500 2WD (Passenger)'), 
('Savana 2500 2WD Conversion (cargo)'), 
('Savana 3500 2WD (cargo)'), 
('Savana 3500 2WD (Passenger)'), 
('Savana Cargo (dedicated CNG)'), 
('Savana Passenger (Bi-fuel)'), 
('Savana Passenger (dedicated CNG)'), 
('Sierra 15 Hybrid 2WD'), 
('Sierra 15 Hybrid 4WD'), 
('Sierra 1500 2WD'), 
('Sierra 1500 4WD'), 
('Sierra 1500 AWD'), 
('Sierra 2500 2WD'), 
('Sierra 2500 4WD'), 
('Sierra 2500 Hd 2WD'), 
('Sierra 2500 HD 2WD CNG'), 
('Sierra 2500 HD 4WD CNG'), 
('Sierra 2WD'), 
('Sierra 4WD'), 
('Sierra 4WD AT4'), 
('Sierra 4WD AT4X'), 
('Sierra C10 2WD'), 
('Sierra C10 Cab Chassis 2WD'), 
('Sierra C10 XFE 2WD'), 
('Sierra C15 2WD'), 
('Sierra C15 Cab Chassis 2WD'), 
('Sierra C15 XFE 2WD'), 
('Sierra Cab Chassis 2WD'), 
('Sierra Cab Chassis 4WD'), 
('Sierra Classic 15 Hybrid 2WD'), 
('Sierra Classic 15 Hybrid 4WD'), 
('Sierra Classic 1500 2WD'), 
('Sierra Classic 1500 4WD'), 
('Sierra Classic 1500 AWD'), 
('Sierra Denali 1500 AWD'), 
('Sierra K10 4WD'), 
('Sierra K10 4WD AT4'), 
('Sierra K10 Cab Chassis 4WD'), 
('Sierra K15 4WD'), 
('Sierra K15 AWD'), 
('Sierra K15 Cab Chassis 4WD'), 
('Sierra LTD C15 2WD'), 
('Sierra LTD K15 4WD'), 
('Sierra Mud Terrain Tires 4WD'), 
('Sonoma 2WD'), 
('Sonoma 2WD (FFV)'), 
('Sonoma 4WD'), 
('T15 (S15) Jimmy 4WD'), 
('T15 (S15) Pickup 4WD'), 
('Terrain AWD'), 
('Terrain FWD'), 
('V15 Jimmy 4WD'), 
('V15 Pickup 4WD'), 
('V15 Suburban 4WD'), 
('V25 Pickup 4WD'), 
('Vandura 2500 2WD'), 
('Vandura G15/25 2WD'), 
('Vandura G15/25 2WD (cargo)'), 
('Vandura G35  2WD'), 
('Vandura G35 2WD'), 
('Vandura G35 2WD (cargo)'), 
('Yukon 1500 2WD'), 
('Yukon 1500 4WD'), 
('Yukon 1500 AWD'), 
('Yukon 1500 Hybrid 2WD'), 
('Yukon 1500 Hybrid 4WD'), 
('Yukon 1500 XFE 2WD'), 
('Yukon 2WD'), 
('Yukon 4WD'), 
('Yukon C10 2WD');