INSERT INTO VehicleModels (Model)
VALUES
('911 GT2 RS'), 
('911 GT3'), 
('911 GT3 RS'), 
('911 GT3 Touring'), 
('911 GTS'), 
('911 GTS Cabriolet'), 
('911 R'), 
('911 SC'), 
('911 Speedster'), 
('911 Sport Classic'), 
('911 Targa'), 
('911 Targa 4'), 
('911 Targa 4 GTS'), 
('911 Targa 4S'), 
('911 Turbo'), 
('911 Turbo Cabriolet'), 
('911 Turbo Coupe'), 
('911 Turbo S'), 
('911 Turbo S Cabriolet'), 
('911 Turbo S Coupe'), 
('911 Turbo S Exclusive'), 
('911 Turbo S Exclusive Cabriolet'), 
('918 Spyder'), 
('924 S'), 
('928 GTS'), 
('928 S'), 
('928 S4'), 
('944 S'), 
('944 S2'), 
('944 Turbo'), 
('Boxster'), 
('Boxster GTS'), 
('Boxster S'), 
('Boxster Spyder'), 
('Boxster T'), 
('Carrera'), 
('Carrera 2 911 GT3'), 
('Carrera 2 Cabriolet'), 
('Carrera 2 Cabriolet Kit'), 
('Carrera 2 Coupe'), 
('Carrera 2 Coupe Kit'), 
('Carrera 2 S Cabriolet'), 
('Carrera 2 S Coupe'), 
('Carrera 4'), 
('Carrera 4 Cabriolet'), 
('Carrera 4 Cabriolet Kit'), 
('Carrera 4 Coupe'), 
('Carrera 4 S'), 
('Carrera 4 S Cabriolet'), 
('Carrera 4 S Cabriolet Kit'), 
('Carrera 4 S Coupe'), 
('Carrera 4 S Kit'), 
('Carrera 4 S Targa'), 
('Carrera 4 Targa'), 
('Carrera GT'), 
('Cayenne'), 
('Cayenne / Cayenne Coupe'), 
('Cayenne Coupe'), 
('Cayenne Diesel'), 
('Cayenne e-Hybrid'), 
('Cayenne e-Hybrid Coupe'), 
('Cayenne GTS'), 
('Cayenne GTS Coupe'), 
('Cayenne Platinum'), 
('Cayenne S'), 
('Cayenne S Coupe'), 
('Cayenne S e-Hybrid'), 
('Cayenne S Hybrid'), 
('Cayenne TransSiberia'), 
('Cayenne Turbo'), 
('Cayenne Turbo Coupe'), 
('Cayenne Turbo GT'), 
('Cayenne Turbo GT Coupe'), 
('Cayenne Turbo Kit'), 
('Cayenne Turbo S'), 
('Cayenne Turbo S e-Hybrid'), 
('Cayenne Turbo S e-Hybrid Coupe'), 
('Cayenne Turbo S/Coupe E-Hybrid'), 
('Cayenne/Coupe E-Hybrid'), 
('Cayman'), 
('Cayman GT4'), 
('Cayman GTS'), 
('Cayman R'), 
('Cayman S'), 
('Cayman T'), 
('Macan'), 
('Macan GTS'), 
('Macan S'), 
('Macan T'), 
('Macan Turbo'), 
('Macan Turbo Kit'), 
('New 911 Carrera'), 
('New 911 Carrera Cabriolet'), 
('New 911 Carrera S'), 
('New 911 Carrera S Cabriolet'), 
('Panamera'), 
('Panamera 4'), 
('Panamera 4 e-Hybrid'), 
('Panamera 4 e-Hybrid Executive'), 
('Panamera 4 e-Hybrid ST'), 
('Panamera 4 E-Hybrid/Exec/ST'), 
('Panamera 4 Executive'), 
('Panamera 4 ST'), 
('Panamera 4S'), 
('Panamera 4S e-Hybrid'), 
('Panamera 4S e-Hybrid Executive'), 
('Panamera 4S e-Hybrid ST'), 
('Panamera 4S e-Hybrid/Exec/ST'), 
('Panamera 4S Executive'), 
('Panamera 4S ST'), 
('Panamera GTS'), 
('Panamera GTS ST'), 
('Panamera S'), 
('Panamera S E-Hybrid'), 
('Panamera S Hybrid'), 
('Panamera Turbo'), 
('Panamera Turbo Exec'), 
('Panamera Turbo Executive'), 
('Panamera Turbo S'), 
('Panamera Turbo S e-Hybrid'), 
('Panamera Turbo S e-Hybrid Executive'), 
('Panamera Turbo S e-Hybrid ST'), 
('Panamera Turbo S E-Hybrid/Exec/ST'), 
('Panamera Turbo S Executive'), 
('Panamera Turbo S ST'), 
('Panamera Turbo S/Exec/ST'), 
('Panamera Turbo ST'), 
('Targa'), 
('Targa Kit'), 
('Taycan 4 Cross Turismo'), 
('Taycan 4S Cross Turismo'), 
('Taycan 4S Perf Battery'), 
('Taycan 4S Perf Battery Plus'), 
('Taycan 4S Performance Battery'), 
('Taycan GTS'), 
('Taycan GTS Sport Turismo'), 
('Taycan GTS ST'), 
('Taycan Perf Battery'), 
('Taycan Perf Battery Plus'), 
('Taycan Performance Battery'), 
('Taycan Turbo'), 
('Taycan Turbo Cross Turismo'), 
('Taycan Turbo S'), 
('Taycan Turbo S Cross Turismo'), 
('Turbo'), 
('Turbo 2 911 GT2'), 
('Turbo 4 911'), 
('Turbo 4 911 Cab'), 
('Turbo 4 911 Cab Kit'), 
('Turbo 4 911 Kit'), 
('Turbo 4 911 S'), 
('Turbo 4 911 Turbo'), 
('Turbo 4 911 Turbo Cab S'), 
('Turbo GT2'), 
('Turbo Kit'), 
('Chevrolet Cavalier'), 
('Detomaso Mangusta'), 
('1500 2WD'), 
('1500 4WD'), 
('1500 Classic 2WD'), 
('1500 Classic 4WD'), 
('1500 HFE 2WD'), 
('1500 TRX 4WD'), 
('C/V'), 
('C/V Cargo Van'), 
('C/V Tradesman'), 
('Promaster City'), 
('Delta 204T'), 
('18i'), 
('18i 4DR Wagon'), 
('18i SportWagon'), 
('Alliance'), 
('Alliance Convertible'), 
('Alliance/Encore'), 
('Fuego'), 
('GTA'), 
('GTA Convertible'), 
('SportWagon'), 
('R1S'), 
('R1S All-Terrain'), 
('R1S All-Terrain Dual Large'), 
('R1S All-Terrain Performance Dual Large'), 
('R1S Performance Dual Large'), 
('R1T'), 
('R1T Dual Large'), 
('Camargue'), 
('Continental (Turbo)'), 
('Corniche'), 
('Corniche II'), 
('Corniche II/Continental'), 
('Corniche III'), 
('Corniche IV'), 
('Corniche S'), 
('Corniche/Continental'), 
('Cullinan'), 
('Cullinan Black Badge'), 
('Dawn'), 
('Dawn Black Badge'), 
('Eight/Mulsan'), 
('Eight/Mulsanne S'), 
('Eight/Mulsanne S and S'), 
('Ghost'), 
('Ghost Black Badge'), 
('Ghost EWB'), 
('Ghost Extended'), 
('Park Ward'), 
('Phantom'), 
('Phantom Coupe'), 
('Phantom Drophead Coupe'), 
('Phantom EWB'), 
('Phantom Extended'), 
('Silver Dawn'), 
('Silver Seraph'), 
('Silver Spirit II/Silver Spur'), 
('Silver Spirit III/Spur III'), 
('Silver Spirit/Silver Spur'), 
('Silver Spirit/Spur/Mulsanne'), 
('Silver Spur'), 
('Silver Spur II Mpw Touring L'), 
('Silver Spur III Limousine'), 
('Silver Spur Limousine'), 
('Silver Spur Park Ward'), 
('Silver Spur/Silver Dawn'), 
('Spirit III/Spur III/Dawn'), 
('Turbo R'), 
('Turbo R/Rl Bklds Turbo/LWB'), 
('Turbo R/Turbo R(lwb)'), 
('Turbo R/Turbo Rl'), 
('Wraith'), 
('Wraith Black Badge'), 
('Boss F150 Super Cab 2WD'), 
('Stage 3 F-150 2WD'), 
('Stage 3 F-150 4WD'), 
('Stage 3 F150 Regular Cab 2WD'), 
('Stage 3 F150 Regular Cab 4WD'), 
('Stage 3 F150 Super Cab 2WD'), 
('Stage 3 F150 Super Cab 4WD'), 
('Stage 3 F150 Super Crew 2WD'), 
('Stage 3 F150 Super Crew 4WD'), 
('Stage 3 F-150 Supercab 2WD'), 
('Stage 3 F-150 Supercab 4WD'), 
('Stage 3 F-150 Supercrew 2WD'), 
('Stage 3 F-150 Supercrew 4WD'), 
('Stage 3 Mustang'), 
('Stage 3 Mustang Coupe'), 
('RUF Turbo 12/CTR3'), 
('RUFTurbo12/CTR3/CTR2017'), 
('Turbo12/CTR3/CTR ANNIVERSARY'), 
('Ruf'), 
('Funeral Coach  2WD'), 
('900'), 
('9000'), 
('9.мар'), 
('9.май'), 
('900 Convertible'), 
('900S'), 
('900S Convertible'), 
('900SE'), 
('900SE Convertible'), 
('9-2x Wagon AWD'), 
('9-3 Aero Sedan AWD'), 
('9-3 Aero SporTCombi AWD'), 
('9-3 Convertible'), 
('9-3 Sedan AWD'), 
('9-3 Sport Sedan'), 
('9-3 SporTCombi'), 
('9-3 Viggen'), 
('9-3 Viggen Convertible'), 
('9-3X SporTCombi AWD'), 
('9-4X AWD'), 
('9-4X FWD'), 
('9-5 Sedan'), 
('9-5 Sedan AWD'), 
('9-5 SporTCombi'), 
('9-5 Wagon'), 
('9-7X AWD'), 
('Convertible'), 
('Mustang S351'), 
('SSC'), 
('F150 Supercharged'), 
('S281 Family'), 
('S331 Family'), 
('Astra 2DR HaTChback'), 
('Astra 4DR HaTChback'), 
('Aura'), 
('Aura Hybrid'), 
('Ion'), 
('L100/200'), 
('L200'), 
('L300'), 
('LW'), 
('LW200'), 
('LW300'), 
('Outlook AWD'), 
('Outlook FWD'), 
('Relay AWD'), 
('Relay FWD'), 
('SKY'), 
('SL'), 
('SW'), 
('Vue AWD'), 
('Vue FWD'), 
('Vue Hybrid'), 
('FR-S'), 
('iA'), 
('iM'), 
('iQ'), 
('iQ EV'), 
('TC'), 
('xA'), 
('xB'), 
('xD'), 
('Mustang GT'), 
('EQ fortwo (convertible)'), 
('EQ fortwo (coupe)'), 
('fortwo cabriolet'), 
('fortwo convertible'), 
('fortwo coupe'), 
('fortwo electric drive cabriolet'), 
('fortwo electric drive convertible'), 
('fortwo electric drive coupe'), 
('C8'), 
('C8 Aileron'), 
('C8 Double 12 S'), 
('C8 Double 12 Spyder'), 
('C8 Laviolette'), 
('C8 Spyder'), 
('C8 Spyder Wide Body'), 
('825'), 
('827'), 
('S209'), 
('3 Door 4WD Turbo'), 
('Ascent'), 
('Ascent Limited/Touring'), 
('Ascent Limited/Touring/Onyx AWD'), 
('B9 Tribeca AWD'), 
('Baja AWD'), 
('Brat 4WD'), 
('BRZ'), 
('BRZ tS'), 
('Crosstrek AWD'), 
('Crosstrek Hybrid AWD'), 
('Crosstrek Wilderness AWD'), 
('Forester AWD'), 
('Forester Wilderness AWD'), 
('HaTChback'), 
('HaTChback 4WD'), 
('Impreza'), 
('Impreza 4-Door'), 
('Impreza 5-Door'), 
('Impreza AWD'), 
('Impreza Sport 4-Door'), 
('Impreza Sport 5-Door'), 
('Impreza Sport AWD'), 
('Impreza Wagon'), 
('Impreza Wagon AWD'), 
('Impreza Wagon/Outback Sport'), 
('Impreza Wagon/Outback Sport AWD'), 
('Impreza Wagon/Outback SPT AWD'), 
('Justy'), 
('Justy 4WD'), 
('Justy AWD'), 
('Legacy'), 
('Legacy 4WD'), 
('Legacy 4WD Turbo'), 
('Legacy AWD'), 
('Legacy AWD (incl. Outback)'), 
('Legacy AWD Turbo'), 
('Legacy Turbo'), 
('Legacy Wagon'), 
('Legacy Wagon 4WD'), 
('Legacy Wagon AWD'), 
('Legacy Wagon AWD (incl. Outback)'), 
('Legacy Wagon AWD Turbo'), 
('Legacy/Outback AWD'), 
('Legacy/Outback Wagon AWD'), 
('Loyale'), 
('Loyale 4WD'), 
('Loyale 4WD Turbo'), 
('Loyale AWD'), 
('Loyale Wagon'), 
('Loyale Wagon 4WD'), 
('Loyale Wagon 4WD Turbo'), 
('Loyale Wagon AWD'), 
('Outback AWD'), 
('Outback Wagon AWD'), 
('Outback Wilderness AWD'), 
('RX Turbo'), 
('Sedan 4WD'), 
('Sedan/3 Door'), 
('Sedan/3 Door 4WD'), 
('Sedan/3Door 4WD Turbo'), 
('Solterra AWD'), 
('Solterra Limited/Touring AWD'), 
('SVX'), 
('SVX AWD'), 
('Tribeca AWD'), 
('Wagon 4WD Turbo'), 
('WRX'), 
('WRX STI Type RA'), 
('XT'), 
('XT 4WD'), 
('XT-DL'), 
('XV Crosstrek AWD'), 
('XV Crosstrek Hybrid AWD'), 
('Aerio'), 
('Aerio 4WD'), 
('Aerio AWD'), 
('Aerio SX'), 
('Aerio SX 4WD'), 
('Aerio SX AWD'), 
('Equator 2WD'), 
('Equator 4WD'), 
('Esteem'), 
('Esteem Wagon'), 
('Forenza'), 
('Forenza Wagon'), 
('Forsa'), 
('Forsa Turbo'), 
('Grand Vitara'), 
('Grand Vitara 4Door 2WD'), 
('Grand Vitara 4Door 4WD'), 
('Grand Vitara 4WD'), 
('Grand Vitara AWD'), 
('Grand Vitara XL7'), 
('Grand Vitara XL7 4WD'), 
('Kizashi'), 
('Kizashi AWD'), 
('Kizashi S'), 
('Kizashi S AWD'), 
('Reno'), 
('SA310'), 
('Samurai'), 
('Samurai 2WD'), 
('Samurai Convertible'), 
('Samurai Hardtop'), 
('Samurai Hardtop 4WD'), 
('Samurai Soft-top 4WD'), 
('Sidekick 2Door 2WD'), 
('Sidekick 2Door 4WD'), 
('Sidekick 2Door RWD'), 
('Sidekick 2WD'), 
('Sidekick 4Door 2WD'), 
('Sidekick 4Door 4WD'), 
('Sidekick 4Door RWD'), 
('Sidekick Convertible 4WD'), 
('Sidekick Hardtop 2WD'), 
('Sidekick Hardtop 4WD'), 
('Sidekick Soft-top 4WD'), 
('Sidekick Sport 2WD'), 
('Sidekick Sport 4WD'), 
('Sidekick Sport RWD'), 
('SJ 410 4WD'), 
('SJ 410V 4WD'), 
('SJ410K P/U 4WD'), 
('Swift'), 
('Swift GA'), 
('Swift GT'), 
('Swift GTI'), 
('Swift x'), 
('SX4'), 
('SX4 AWD'), 
('SX4 Sedan'), 
('SX4 Sport'), 
('SX4 Sport/Anniversary Edition'), 
('Verona'), 
('Vitara 2 Door'), 
('Vitara 2 Door 4WD'), 
('Vitara 2Door'), 
('Vitara 2Door 2WD'), 
('Vitara 2Door 4WD'), 
('Vitara 4 Door'), 
('Vitara 4 Door 4WD'), 
('Vitara 4Door'), 
('Vitara 4Door 2WD'), 
('Vitara 4Door 4WD'), 
('X-90 2WD'), 
('X-90 4WD'), 
('X-90 RWD'), 
('XL7 AWD'), 
('XL7 FWD'), 
('Foose F150 Regular Cab 2WD'), 
('Foose F150 Regular Cab 4WD'), 
('Foose F150 Super Cab 2WD'), 
('Foose F150 Super Cab 4WD'), 
('Foose F150 Super Crew 2WD'), 
('Foose F150 Super Crew 4WD'), 
('Model 3 Long Range'), 
('Model 3 Long Range  AWD'), 
('Model 3 Long Range  AWD Performance'), 
('Model 3 Long Range AWD'), 
('Model 3 Long Range AWD Performance'), 
('Model 3 Long Range Performance AWD (18in)'), 
('Model 3 Long Range Performance AWD (19in)'), 
('Model 3 Long Range Performance AWD (20in)'), 
('Model 3 Mid Range'), 
('Model 3 Performance AWD'), 
('Model 3 RWD'), 
('Model 3 Standard Range'), 
('Model 3 Standard Range Plus'), 
('Model 3 Standard Range Plus RWD'), 
('Model S'), 
('Model S (40 kW-hr battery pack)'), 
('Model S (60 kW-hr battery pack)'), 
('Model S (70 kW-hr battery pack)'), 
('Model S (75 kW-hr battery pack)'), 
('Model S (85 kW-hr battery pack)'), 
('Model S (90 kW-hr battery pack)'), 
('Model S 100D'), 
('Model S 75D'), 
('Model S 75kWh'), 
('Model S AWD - 100D'), 
('Model S AWD - 60D'), 
('Model S AWD - 70D'), 
('Model S AWD - 75D'), 
('Model S AWD - 85D'), 
('Model S AWD - 90D'), 
('Model S AWD - P100D'), 
('Model S AWD - P85D'), 
('Model S AWD - P90D'), 
('Model S AWD (85 kW-hr battery pack)'), 
('Model S Long Range'), 
('Model S Long Range Plus'), 
('Model S P100D'), 
('Model S Performance'), 
('Model S Plaid'), 
('Model S Standard Range'), 
('Model X'), 
('Model X 100D'), 
('Model X 75D'), 
('Model X AWD - 100D'), 
('Model X AWD - 60D'), 
('Model X AWD - 75D'), 
('Model X AWD - 90D'), 
('Model X AWD - P100D'), 
('Model X AWD - P90D'), 
('Model X Long Range'), 
('Model X Long Range Plus'), 
('Model X P100D'), 
('Model X Performance'), 
('Model X Plaid'), 
('Model X Standard Range'), 
('Model Y AWD'), 
('Model Y Long Range AWD'), 
('Model Y Performance AWD'), 
('Model Y RWD'), 
('Model Y Standard Range RWD'), 
('500 SEC'), 
('86'), 
('1-Ton Truck 2WD'), 
('4Runner 2WD'), 
('4Runner 4WD'), 
('Avalon'), 
('Avalon AWD'), 
('Avalon Hybrid'), 
('Avalon Hybrid XLE'), 
('Avalon TRD'), 
('Avalon XLE'), 
('bZ4X'), 
('bZ4X AWD'), 
('bZ4X LIMITED'), 
('bZ4X LIMITED AWD'), 
('Cab Chassis 2WD'), 
('Cab/Chassis'), 
('Cab/Chassis 2WD'), 
('Camry'), 
('Camry AWD LE/SE'), 
('Camry AWD XLE/XSE'), 
('Camry CNG'), 
('Camry Hybrid'), 
('Camry Hybrid LE'), 
('Camry Hybrid SE/XLE/XSE'), 
('Camry Hybrid XLE'), 
('Camry Hybrid XLE/SE'), 
('Camry LE/SE'), 
('Camry Solara'), 
('Camry Solara Convertible'), 
('Camry TRD'), 
('Camry Wagon'), 
('Camry XLE/XSE'), 
('Camry XSE'), 
('Cargo Van 2WD'), 
('Cargo Van 4WD'), 
('Celica'), 
('Celica Convertible'), 
('Celica Supra'), 
('C-HR'), 
('Corolla'), 
('Corolla All-Trac Wagon'), 
('Corolla APEX'), 
('Corolla Cross'), 
('Corolla Cross 4WD'), 
('Corolla FX'), 
('Corolla HaTChback'), 
('Corolla HaTChback XSE'), 
('Corolla Hybrid'), 
('Corolla Hybrid AWD'), 
('Corolla iM'), 
('Corolla LE Eco'), 
('Corolla Sport'), 
('Corolla Wagon'), 
('Corolla XLE'), 
('Corolla XSE'), 
('Cressida'), 
('Cressida Wagon'), 
('Crown AWD'), 
('Echo'), 
('FJ Cruiser 2WD'), 
('FJ Cruiser 4WD'), 
('GR 86'), 
('GR Corolla'), 
('GR Supra'), 
('Grand Highlander AWD LE/XLE'), 
('Grand Highlander AWD Limited/Platinum'), 
('Grand Highlander Hybrid'), 
('Grand Highlander Hybrid AWD'), 
('Grand Highlander Hybrid Limited'), 
('Grand Highlander LE/XLE'), 
('Grand Highlander Limited'), 
('Highlander'), 
('Highlander 2WD'), 
('Highlander 4WD'), 
('Highlander AWD'), 
('Highlander AWD LE'), 
('Highlander Hybrid'), 
('Highlander Hybrid 2WD'), 
('Highlander Hybrid 4WD'), 
('Highlander Hybrid AWD'), 
('Highlander Hybrid AWD LE Plus'), 
('Highlander Hybrid AWD LTD/PLAT'), 
('Highlander LE/XLE/SE/LTD'), 
('Land Cruiser Wagon 4WD'), 
('Matrix'), 
('Matrix AWD'), 
('MR2'), 
('Paseo'), 
('Paseo Convertible'), 
('Previa'), 
('Previa All-Trac'), 
('Prius'), 
('Prius AWD'), 
('Prius AWD XLE/LTD'), 
('Prius c'), 
('Prius Eco'), 
('Prius Plug-in Hybrid'), 
('Prius Prime'), 
('Prius v'), 
('Prius XLE/LTD'), 
('RAV4'), 
('RAV4 2WD'), 
('RAV4 4WD'), 
('RAV4 AWD'), 
('RAV4 AWD LE'), 
('RAV4 AWD TRD OFFROAD'), 
('RAV4 EV'), 
('RAV4 Hybrid  AWD'), 
('RAV4 Hybrid AWD'), 
('RAV4 Hybrid AWD Woodland Edition'), 
('RAV4 LE/XLE'), 
('RAV4 Limited AWD'), 
('RAV4 Limited AWD/SE AWD'), 
('RAV4 Prime 4WD'), 
('RAV4 Soft Top 2WD'), 
('RAV4 Soft Top 4WD'), 
('Sequoia 2WD'), 
('Sequoia 4WD'), 
('Sequoia 4WD FFV'), 
('Sienna 2WD'), 
('Sienna 4WD'), 
('Sienna AWD'), 
('Sienna Hybrid 2WD'), 
('Sienna Hybrid AWD'), 
('Starlet'), 
('Supra'), 
('T100 2WD'), 
('T100 4WD'), 
('Tacoma 2WD'), 
('Tacoma 4WD'), 
('Tacoma 4WD D-CAB MT TRD-ORP/PRO'), 
('Tacoma 4WD Double Cab'), 
('Tacoma 4WD Double Cab Off-Road'), 
('Tacoma 4WD TRD PRO'), 
('Tercel'), 
('Tercel EZ'), 
('Tercel Wagon'), 
('Tercel Wagon 2WD'), 
('Tercel Wagon 4WD'), 
('Truck 2WD/T100 2WD'), 
('Truck 4WD/T100 4WD'), 
('Tundra 2WD'), 
('Tundra 2WD FFV'), 
('Tundra 4WD'), 
('Tundra 4WD FFV'), 
('Tundra 4WD PRO'), 
('Van 2WD'), 
('Van 2WD (cargo)'), 
('Van 2WD (passenger)'), 
('Van 4WD'), 
('Van 4WD (cargo)'), 
('Van 4WD (passenger)'), 
('Venza'), 
('Venza 4WD'), 
('Venza AWD'), 
('Yaris'), 
('Yaris iA'), 
('TVR 280i Convertible'), 
('TVR 280i Coupe'), 
('TVR 280i/350i Convertible'), 
('TVR 280i/350i Coupe'), 
('Avtech SC / M12'), 
('W8'), 
('VF 8 Eco'), 
('VF 8 Plus'), 
('21 TD'), 
('Niva'), 
('Arteon'), 
('Arteon 4motion'), 
('Atlas'), 
('Atlas 4motion'), 
('Atlas 4motion Peak Edition'), 
('Atlas Cross Sport'), 
('Atlas Cross Sport 4motion'), 
('Atlas SE 4motion'), 
('Atlas SEL 4motion'), 
('Beetle'), 
('Beetle Convertible'), 
('Beetle Dune'), 
('Beetle Dune Convertible'), 
('Cabrio'), 
('CC'), 
('CC 4motion'), 
('Corrado'), 
('Corrado SLC'), 
('e-Golf'), 
('Eos'), 
('Eurovan'), 
('Eurovan Camper'), 
('Fox'), 
('Fox GL Wagon'), 
('Fox Wagon'), 
('GLI'), 
('Golf'), 
('Golf Alltrack'), 
('Golf III'), 
('Golf III / GTI'), 
('Golf R'), 
('Golf SportWagen'), 
('Golf SportWagen 4motion'), 
('Golf/GTI'), 
('Golf-R'), 
('GTI'), 
('GTI 16v'), 
('GTI VR6'), 
('GTI/Golf GT'), 
('ID.4'), 
('ID.4 1st'), 
('ID.4 AWD Pro'), 
('ID.4 AWD Pro S'), 
('ID.4 Pro'), 
('ID.4 Pro S'), 
('ID.4 S'), 
('Jetta'), 
('Jetta GLI'), 
('Jetta GLI 16v'), 
('Jetta GLI/Wolfsburg Edition'), 
('Jetta GLX'), 
('Jetta Hybrid'), 
('Jetta III'), 
('Jetta III GLX'), 
('Jetta SE/SEL'), 
('Jetta Sport/SE/SEL'), 
('Jetta SportWagen'), 
('Jetta Wagon'), 
('New Beetle'), 
('New Beetle Convertible'), 
('New Golf'), 
('New GTI'), 
('New Jetta'), 
('Passat'), 
('Passat 4motion'), 
('Passat Syncro'), 
('Passat Wagon'), 
('Passat Wagon 4motion'), 
('Passat Wagon Syncro'), 
('Quantum'), 
('Quantum Syncro Wagon'), 
('Quantum Wagon'), 
('R32'), 
('Rabbit'), 
('Rabbit Convertible'), 
('Routan'), 
('Routan FWD'), 
('Scirocco'), 
('Scirocco 16v'), 
('Taos'), 
('Taos 4motion'), 
('Tiguan'), 
('Tiguan 4motion'), 
('Tiguan Limited'), 
('Tiguan Limited 4motion'), 
('Tiguan R-Line 4motion'), 
('Tiguan S'), 
('Touareg'), 
('Touareg Hybrid'), 
('Vanagon 2WD'), 
('Vanagon Syncro 4WD'), 
('Vanagon/Camper 2WD'), 
('240'), 
('740'), 
('760'), 
('780'), 
('850'), 
('940'), 
('960'), 
('240 DL/240 GL'), 
('240 DL/GL/Turbo'), 
('240 DL/GL/Turbo Wagon'), 
('240 Wagon'), 
('740 16-Valve'), 
('740 16-Valve Wagon'), 
('740 Wagon'), 
('740/760'), 
('740/760 Wagon'), 
('760 GLE'), 
('760 Wagon'), 
('850 Wagon'), 
('940 GLE 16-Valve'), 
('940 GLE 16-Valve Wagon'), 
('940 SE'), 
('940 SE Wagon'), 
('940 Turbo'), 
('940 Turbo Wagon'), 
('940 Wagon'), 
('960 Wagon'), 
('960 Wagon/V90'), 
('960/S90'), 
('C30 FWD'), 
('C40 Recharge'), 
('C40 Recharge twin'), 
('C70'), 
('C70 Convertible'), 
('C70 Coupe'), 
('C70 FWD'), 
('New C70 Convertible'), 
('S40 AWD'), 
('S40 FWD'), 
('S60'), 
('S60 AWD'), 
('S60 AWD PHEV'), 
('S60 B5'), 
('S60 B5 AWD'), 
('S60 CC AWD'), 
('S60 FWD'), 
('S60 Inscription AWD'), 
('S60 Inscription FWD'), 
('S60 Polestar AWD'), 
('S60 R AWD'), 
('S60 T8 AWD Recharge'), 
('S60 T8 AWD Recharge ext. Range'), 
('S70'), 
('S70 AWD'), 
('S80'), 
('S80 AWD'), 
('S80 FWD'), 
('S80/S80 Executive'), 
('S80/S80 Premier'), 
('S90'), 
('S90 AWD'), 
('S90 AWD PHEV'), 
('S90 B6 AWD'), 
('S90 FWD'), 
('S90 T8 AWD Recharge'), 
('S90 T8 AWD Recharge ext. Range'), 
('V40'), 
('V50 AWD'), 
('V50 FWD'), 
('V60 AWD'), 
('V60 AWD PHEV'), 
('V60 CC AWD'), 
('V60 CC FWD'), 
('V60 FWD'), 
('V60 Polestar AWD'), 
('V60 T8 AWD Recharge'), 
('V60 T8 AWD Recharge ext. Range'), 
('V60CC B5 AWD'), 
('V60CC T5 AWD'), 
('V70 AWD'), 
('V70 FWD'), 
('V70 R AWD'), 
('V70 XC AWD'), 
('V90'), 
('V90 AWD'), 
('V90 CC AWD'), 
('V90 FWD'), 
('V90CC B6 AWD'), 
('XC40 AWD'), 
('XC40 AWD BEV'), 
('XC40 B4'), 
('XC40 B5 AWD'), 
('XC40 FWD'), 
('XC40 Recharge'), 
('XC40 Recharge twin'), 
('XC40 T4'), 
('XC40 T5 AWD'), 
('XC60 AWD'), 
('XC60 AWD PHEV'), 
('XC60 B5'), 
('XC60 B5 AWD'), 
('XC60 B6 AWD'), 
('XC60 FWD'), 
('XC60 T8 AWD Recharge'), 
('XC60 T8 AWD Recharge ext. Range'), 
('XC70 AWD'), 
('XC70 FWD'), 
('XC90 AWD'), 
('XC90 AWD PHEV'), 
('XC90 B5 AWD'), 
('XC90 B6 AWD'), 
('XC90 FWD'), 
('XC90 T5'), 
('XC90 T5 AWD'), 
('XC90 T6 AWD'), 
('XC90 T8 AWD Recharge'), 
('XC90 T8 AWD Recharge ext. Range'), 
('Wetl 190E'), 
('Wetl 190E 2.3'), 
('Wetl 300 CE'), 
('Wetl 300 E'), 
('Wetl 300 GE'), 
('Wetl 300 SL'), 
('Wetl 300 TE'), 
('Wetl 412'), 
('Wetl 500 SE'), 
('Wetl 500 SEC'), 
('Wetl 500 SEL'), 
('Wetl 500 SL'), 
('Wetl 560 SEC'), 
('Wetl 560 SEL'), 
('Wetl 560 SL'), 
('Wetl 600 SEL'), 
('Wetl 850I'), 
('Wetl Testarossa'), 
('GV'), 
('GV Plus/GV/Cabrio'), 
('GV/GVX'), 
('Gy/yugo GVX');